In [10]:
import csv
import pandas as pd
import json
import requests
import numpy as np
import os
import time
import math
from collections import defaultdict
from scipy.stats.mstats import winsorize
from datetime import datetime
from dateutil.relativedelta import relativedelta

# PATH = "C:/Udemy/2026-Python-EricBanas/Banas/Section53_Finance/redo/"
PATH = "D:/Udemy/2026-Python3-ErikBanas/Section53_PythonForFinance/redo/"
tickers_to_skip = ['SEB']
missing_tickers = []

# pd.set_option('display.max_colwidth', 500)


HEADERS = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiaGVjdG9yYXdzQHlhaG9vLmNvbSIsInBsYW4iOiJwcm8iLCJuZXdzZmVlZF9lbmFibGVkIjp0cnVlLCJ3ZWJzb2NrZXRfc3ltYm9scyI6Miwid2Vic29ja2V0X2Nvbm5lY3Rpb25zIjoxfQ.eXXJXl0mETrgv_aITIsjl_tmT3HQ-RdsiRCw-54NWlw',
    }
# TODO: add def to get ticker info for country

# My Recommendation

# Your next steps should probably be:

# Finish sector screeners
# Select top stocks per sector
# Build covariance matrix
# Calculate:
    # portfolio return
    # volatility
    # Sharpe ratio
    # Plot efficient frontier
# Compare:
    # equal weight
    # optimized portfolio

# That is a very strong investing research pipeline.

In [11]:

%%html
<style>
    .dataframe th { font-size: 12px; }
    .dataframe td { font-size: 12px; }
    .dataframe {width:100%}
    .dataframe tr > td:last { width:30% }
</style>

In [12]:
sec_df = pd.read_csv(PATH + 'sector-stocks/stock_sectors.csv')
ener_df = sec_df.loc[sec_df['Sector'] == "energy"]
energy = get_rois_for_stocks(ener_df, '2025-01-01','2026-04-15')
energy = energy.sort_values(by='Ticker')
energy

File for ticker BRN doesn't exist
File for ticker BATL doesn't exist
File for ticker CKX doesn't exist
File for ticker DNN doesn't exist
File for ticker EP doesn't exist
File for ticker UUUU doesn't exist
File for ticker EONR doesn't exist
File for ticker EPM doesn't exist
File for ticker GTE doesn't exist
File for ticker IMO doesn't exist
File for ticker INDO doesn't exist
File for ticker ISOU doesn't exist
File for ticker JAGU doesn't exist
File for ticker MXC doesn't exist
File for ticker NINE doesn't exist
File for ticker OBE doesn't exist
File for ticker PED doesn't exist
File for ticker REPX doesn't exist
File for ticker REI doesn't exist
File for ticker TMDE doesn't exist
File for ticker TOPS doesn't exist
File for ticker TPET doesn't exist
File for ticker UEC doesn't exist
File for ticker URG doesn't exist

    Ticker                       Company classification       ROI
168   ACDC         ProFrac Holding Corp.       upstream -0.249093
62     AEC           Anfield Energy Inc.       upstream  0.249583
37    AESI   Atlas Energy Solutions Inc.   oil_services -0.396844
17      AM  Antero Midstream Corporation      midstream  0.466395
61    AMPY          Amplify Energy Corp.       upstream -0.098361
..     ...                           ...            ...       ...
222    WTI            W&T Offshore, Inc.       upstream  0.663449
181   WTTR  Select Water Solutions, Inc.       upstream  0.126592
7      XOM       Exxon Mobil Corporation     integrated  0.449152
101   XPRO     Expro Group Holdings N.V.       upstream  0.262500
227    YPF       YPF Sociedad AnÃƒÂ³nima       upstream -0.068610

[228 rows x 4 columns]

In [13]:
# def get_max_consecutive_positive_years(values, num_of_consec_years):
#     try:
#         years = 0
#         for i in range (len(values)):
#             if values[i] is not None:
#                 if values[i] < 0:
#                   years = 0  
#                 elif values[i] > 0:
#                     years += 1
#                     if years == num_of_consec_years:
#                         return True
#             else:
#                 years = 0  
#     except Exception as e:
#         print (f'Error in get_max_consecutive_positive_years {e} {values} {num_of_consec_years}')
#         return False
#     else:
#         return False

In [14]:

# def get_has_consecutive_years_positive_fcf2(values, num_of_consec_years = 10):
#     consec_years, score, final_score_reached = 0, 0, False
#     max_score = 0
#     years_counted = 0
    
#     for i in range(len(values)):
#         if values[i] is not None:
#             years_counted += 1            
#             if values[i] > 0:
#                 consec_years += 1
#                 if consec_years == num_of_consec_years:
#                     final_score_reached = True
#                     break
#             else:
#                 score = 0
#                 consec_years = 0
                
#     if final_score_reached == True:
#         return num_of_consec_years > 0, years_counted - num_of_consec_years
        
#     return False, 0

# def get_blue_chip_score_for_consecutive_years(values):
#     weights = np.linspace(len(values), 1, len(values)) / len(values) - 1
#     weights = weights[::-1] 
#     blue_chip_score = 3
#     years = 0
#     result, starting_year = get_has_consecutive_years_positive_fcf2(values, 15)
#     if result == True:    
#         blue_chip_score -= (1 + weights[starting_year])
#         years = 15
#     else:
#         result, starting_year = get_has_consecutive_years_positive_fcf2(values, 10)
#         if result == True:
#             blue_chip_score -= (2 * (1 + weights[starting_year]))
#             years = 10
#         else:
#             result, starting_year = get_has_consecutive_years_positive_fcf2(values, 5)
#             if result == True:
#                 blue_chip_score -= (3 * (1 + weights[starting_year]))
#                 years = 5
#             else:
#                 result, starting_year = get_has_consecutive_years_positive_fcf2(values, 3)
#                 if result == True:
#                     blue_chip_score -= 4 * (1 + weights[starting_year])
#                     years = 3
#                 else:
#                     blue_chip_score -= 5
                    
#     return float(blue_chip_score), years

In [15]:
def has_consecutive_positive_fcf(values, required_years):
    consec = 0
    
    for i, value in enumerate(values):
        if value is None:
            continue

        if value > 0:
            consec += 1
            if consec >= required_years:
                start_index = i - required_years + 1
                return True, start_index
        else:
            consec = 0

    return False, 0


def get_blue_chip_score_for_consecutive_years(values):
    if not values:
        return 0.0, 0

    # oldest = 0.0, newest = 1.0
    recency_weights = np.linspace(0.0, 1.0, len(values))
    recency_weights = recency_weights[::-1]

    # years, base_score
    streak_rules = [
        (15, 3.0),
        (10, 2.5),
        (5, 2.0),
        (3, 1.5),
    ]

    for required_years, base_score in streak_rules:
        result, start_index = has_consecutive_positive_fcf(values, required_years)
        
        if result:
            recency_bonus = recency_weights[start_index]
            final_score = base_score + recency_bonus
            # print ('required_years:', required_years, 'start_index:', start_index, 'base_score:', base_score, 'recency_bonus:', recency_bonus, 'final_score:', final_score)            
            return float(final_score), required_years

    return 0.0, 0

In [16]:
test_tickers = ['BP','CNQ','CVE','CVX','COP','E','EQNR','XOM','OXY','SHEL','TTE','TMDE']
                
                # test_tickers = ['BP','CNQ','CVE','CVX','COP','E','EQNR','XOM','OXY','SHEL','TTE','TMDE',
# 'TOPS',
# 'TRMD',
# 'TORO',
# 'TGS',
# 'TPET',
# 'TEN',
# 'TXO',
# 'USEG',
# 'UGP',
# 'UEC',
# 'UROY',
# 'URG',
# 'EGY',
# 'VAL',
# 'VG',
# 'VET',
# 'VNOM',
# 'VIST',
# 'VTS',
# 'VIVK',
# 'VOC',
# 'WTI',
# 'WBI',
# 'WFRD',
# 'WDS',
# 'WKC',
# 'YPF',
# 'SM',
# 'SND',
# 'SEI',
# 'SOBO',
# 'SLNG',
# 'STAK',
# 'SGU',
# 'SMC',
# 'SU',
# 'SUN',
# 'SUNC',
# 'TALO',
# 'TBN',
# 'TRGP',
# 'TRP',
# 'FTI',
# 'TK',
# 'TNK',
# 'TS']

In [17]:
def get_formatted_data(sector_df, trace = False):
    # data = {
    #     "AAPL": {
            # "pe": [35, 32, 29],
            # "ev_sales": [12, 10, 8],
            # "revenue_growth": [0.12, 0.15, 0.18],
            # "operating_margin": [0.38, 0.40, 0.42],
            # "rule_of_40": [37, 43, 49],
            # "sector": "Technology"
            # ...
    #     },
    # }
    
    data = None    
    tickers, betas, rois = [], [], []

    revs = []
    
    # fcf_pos_year_5s = []

    free_cash_flow_fy_hs = []
    
    fcf_yields = []
    fcf_yields_hs = []
    price_return_1ys = []
    countries = []
    net_debt_to_ebitdas = []
    net_debt_to_ebitda_hs = []
    
    dividend_yield_recents = []
    
    dividend_payout_ratio_fys = []
    dividend_payout_ratio_fy_hs = []
    
    enterprise_value_ebitda_ttms = []
    enterprise_value_ebitda_fq_hs = []
    classifications = []
    operating_margin_ttms = []
    operating_margin_fy_hs = []
    return_on_invested_capitals = []
    return_on_invested_capital_fy_hs = []
    
    pe_fy_hs = []
    price_earnings_currents = []

    eps_dilu_ttms, eps_dil_fy_hs, eps_frcst_next_fy = [], [], []

    dil_shrs_outstand_fy_hs = []
    # share_buyback_fy_ratios = []

    fcf_p_share_ttms = []
    fcf_p_share_fy_hs = []

    ev_to_sales_ttms = []
    ev_to_sales_hs = []
    ev_to_sales_currents = []

    current_ratios = []
    current_ratios_hs = []
    
    interest_coverages = []

    total_revenue_fy_hs = []

    market_caps = []

    share_change_pcts = []
    all_share_changes = []

    dividend_payments = []
    
    counter = 0
    for ticker in energy['Ticker'].values.tolist():
        
        try:
            
            if ticker not in test_tickers:
                continue

            
            data = get_jsondata_from_file('dividends', ticker)
            # print (0)
            
            if data is None:
                continue
            # print (1)
            
            if data.get('data') is None:
                continue
            
            data = data['data']
            
            # print (2)
            
            if len(data) == 0:
                continue
                
            

            # latest_diluted_shares = get_stock_info(ticker,'total_shares_outstanding')
            # if latest_diluted_shares is None:
            #     continue
                
            return_on_invested_capital = get_single_value(ticker, data, "return_on_invested_capital")

            if return_on_invested_capital is None:
                continue
        
            return_on_invested_capital_fy_h = get_history_indicator_values(ticker, data, 'return_on_invested_capital_fy_h', 5)
            
            operating_margin_fy_h = get_history_indicator_values(ticker, data, 'operating_margin_fy_h', 99)
            operating_margin_ttm = get_single_value(ticker, data, "operating_margin_ttm") 

            free_cash_flow_fy_h = next((item for item in data if item["id"] == 'free_cash_flow_fy_h'), None) 
            free_cash_flow_fy_h = free_cash_flow_fy_h['value']
                
            
            total_revenue_fy_h = get_history_indicator_values(ticker, data, 'total_revenue_fy_h', 6)
            
            # print (4)
            
            pe_fy_history = get_history_indicator_values(ticker, data, 'price_earnings_fy_h', 3)
            price_earnings_current = get_single_value(ticker, data, 'price_earnings_current')

            # print (6)
            
            beta = next((item for item in data if item["id"] == 'beta_5_year'), None) 
            
            fcf_ttm_value = get_single_value(ticker, data, "free_cash_flow_ttm")
            
            net_debt_to_ebitda = get_single_value(ticker, data, "net_debt_to_ebitda_fy")
            
            dividend_yield_recent = get_single_value(ticker, data, "dividend_yield_recent")

            # print (7)
            
            dividend_payout_ratio_fy = get_single_value(ticker, data, "dividend_payout_ratio_fy")
            dividend_payout_ratio_fy_h = get_history_indicator_values(ticker, data, "dividend_payout_ratio_fy_h", 3)

            # print (8)

            enterprise_value_ebitda_ttm = get_single_value(ticker, data, "enterprise_value_ebitda_ttm")
            enterprise_value_ebitda_fq_h = get_history_indicator_values(ticker, data, "enterprise_value_ebitda_fq_h", 3)
            enterprise_value_fy_h = get_history_indicator_values(ticker, data, 'enterprise_value_fy_h', 5)

            earnings_per_share_diluted_ttm = get_single_value(ticker, data, "earnings_per_share_diluted_ttm")
            earnings_per_share_diluted_fy_h = get_history_indicator_values(ticker, data, "earnings_per_share_diluted_fy_h", 3)
            earnings_per_share_forecast_next_fy = get_single_value(ticker, data, "earnings_per_share_forecast_next_fy")

            total_debt_fy_h = get_history_indicator_values(ticker, data, "total_debt_fy_h", 3)
            
            cash_n_equivalents_fy_h = get_history_indicator_values(ticker, data, "cash_n_equivalents_fy_h", 3)
            
            ebitda_fy_h = get_history_indicator_values(ticker, data, "ebitda_fy_h", 3)

            dil_shrs_outstand_fy_h = get_history_indicator_values(ticker, data, "diluted_shares_outstanding_fy_h", 5)
            
            # fcf_h_3_yrs = get_history_indicator_values(ticker, data, 'free_cash_flow_fy_h', 3)
            fcf_h_5_yrs = get_history_indicator_values(ticker, data, 'free_cash_flow_fy_h', 5)
            

            fcf_p_share = get_single_value(ticker, data, "free_cash_flow_per_share_current")
            fcf_p_share_fy_h = get_history_indicator_values(ticker, data, "free_cash_flow_per_share_fy_h", 3)

            current_assets = get_single_value(ticker, data, "total_current_assets_fy")
            current_liabilities = get_single_value(ticker, data, "total_current_liabilities_fy")

            current_assets_fy_h = get_history_indicator_values(ticker, data, "total_current_assets_fy_h", 3)
            current_liabilities_fy_h = get_history_indicator_values(ticker, data, "total_current_liabilities_fy_h", 3)

            ebit_fy_h = get_history_indicator_values(ticker, data, "ebit_fy_h", 3)
            # ebit_ttm = get_single_value(ticker, data, "ebit_ttm")
            
            interest_expense_on_debt_fy_h = get_history_indicator_values(ticker, data, "interest_expense_on_debt_fy_h", 3)
            
            dividend_payment_date_h = get_history_indicator_values(ticker, data, "dividend_payment_date_h", 40)
            dividend_amount_h = get_history_indicator_values(ticker, data, "dividend_amount_h", 40)

            
            close = get_close(ticker)

            
            if close == -1 or operating_margin_fy_h is None or operating_margin_ttm is None:
                continue
            
            if earnings_per_share_diluted_ttm is None:
                continue
                
            if fcf_ttm_value is None:
                continue

            if earnings_per_share_forecast_next_fy is None:
                continue
                
            if fcf_p_share is None or fcf_p_share_fy_h is None:
                continue

            if dividend_yield_recent is None:
                continue

            if enterprise_value_ebitda_ttm is None:
                continue

            if has_acceptable_beta(0, 10, beta) == False or sequence_has_zeros_or_none(total_revenue_fy_h) == True or sequence_has_zeros_or_none(pe_fy_history) == True:
                continue

            if current_assets is None or current_liabilities is None:
                continue

            if enterprise_value_ebitda_ttms is None:
                continue

            if enterprise_value_ebitda_fq_h is None:
                continue

            if ebit_fy_h is None:
                continue
                
            if interest_expense_on_debt_fy_h is None:
                continue

                
            #------------------------
            # process the stock data
            #------------------------

            shares_outstanding = get_stock_info(ticker, "current_total_shares_outstanding")                          
            market_cap = shares_outstanding * close

            market_caps.append(market_cap)
            
            tickers.append(ticker)

            
            if trace:
                print (1)

            countries.append(get_country_from_website_url(get_stock_info(ticker, 'website')))

            if trace:
                print (1.1, earnings_per_share_forecast_next_fy)
                 

            eps_dilu_ttms.append(np.around(earnings_per_share_diluted_ttm, decimals=2))
            eps_dil_fy_hs.append(np.around(earnings_per_share_diluted_fy_h, decimals=2).tolist())
            eps_frcst_next_fy.append(np.around(earnings_per_share_forecast_next_fy, decimals=2))
                
            classifications.append(sector_df[sector_df['Ticker'] == ticker]['classification'].item())
            
            rois.append(sector_df[sector_df['Ticker'] == ticker]['ROI'].item())

            
            if trace:
                print ('1.1.1')

                
            price_1yr_ago = get_one_year_ago_price(ticker)

            
            if trace:
                print ('1.1.2')

                
            return_1yr_ago = round(((close - price_1yr_ago) / price_1yr_ago) * 100, 2)
            
            if trace:
                print ('1.1.3')

                
            price_return_1ys.append(return_1yr_ago)

            
            if trace:
                print (1.2)
            
            dividend_yield_recents.append(round(dividend_yield_recent, 2))


            if dividend_payout_ratio_fy is not None:
                dividend_payout_ratio_fys.append(round(dividend_payout_ratio_fy, 2))
            else:
                dividend_payout_ratio_fys.append(0)
                
            dividend_payout_ratio_fy_hs.append(dividend_payout_ratio_fy_h)

            
            if trace:
                print (2)
            

            return_on_invested_capitals.append(np.around(return_on_invested_capital * 100, decimals=2))

            return_on_invested_capital_fy_h = convert_none_to_zero_in_list(return_on_invested_capital_fy_h)
            return_on_invested_capital_fy_hs.append(np.around(np.array(return_on_invested_capital_fy_h), decimals=2).tolist())

            operating_margin_ttms.append(np.around(operating_margin_ttm, decimals=2))

            operating_margin_fy_h = convert_none_to_zero_in_list(operating_margin_fy_h)
            operating_margin_fy_hs.append(np.around(np.array(operating_margin_fy_h), decimals=2).tolist())

            
            if trace:
                print (2)

            total_revenue_fy_hs.append(total_revenue_fy_h)

            if trace:
                print (2.5)

            
            free_cash_flow_fy_h = [x for x in free_cash_flow_fy_h if x is not None]
            free_cash_flow_fy_hs.append(free_cash_flow_fy_h)
            
            if trace:
                print (2.6)
            
            #  EV to Sales
            total_debt = get_single_value(ticker, data, "total_debt_fq")
            cash = get_single_value(ticker, data, "cash_n_equivalents_fy")

            if trace:
                print (2.7)
                
            enterprise_value = market_cap + total_debt - cash
            latest_total_revenue = get_stock_info(ticker,  'total_revenue', False)
            ev_to_sales_currents.append(round((enterprise_value / latest_total_revenue), 2)  )

  
            if trace:
                print (2.8)
                
            # Ev to Sales history

            # total_revenue_fy_h = total_revenue_fy_h[1:]
            
            enterprise_value_fy_h_series = np.array(enterprise_value_fy_h[-5:])
            total_reveue_fy_h_series = np.array(total_revenue_fy_h[-5:])

            # print (ticker, 'enterprise_value_fy_h_series',enterprise_value_fy_h_series)
            # print ('total_reveue_fy_h_series',total_reveue_fy_h_series)

            
            ev_to_sales_hs.append(np.around(enterprise_value_fy_h_series / total_reveue_fy_h_series, decimals=2).tolist())

            
            if trace:
                print (2.9)


            enterprise_value_ebitda_fq_h = remove_nones_from_list(enterprise_value_ebitda_fq_h)
            enterprise_value_ebitda_fq_h = np.around(np.array(enterprise_value_ebitda_fq_h), decimals=2).tolist()
            enterprise_value_ebitda_fq_hs.append(enterprise_value_ebitda_fq_h)
            
            enterprise_value_ebitda_ttms.append(np.around(enterprise_value_ebitda_ttm, decimals=2))
            
            if trace:
                print (3)
                
            pe_fy_hs.append(np.around(np.array(pe_fy_history), decimals=2).tolist())
            price_earnings_currents.append(price_earnings_current)

            
            net_debt_to_ebitdas.append(np.around(net_debt_to_ebitda, decimals=2))

            if trace:
                print (4)
    
            
            net_debt_ebitda_numerator = np.array(total_debt_fy_h)  - np.array(cash_n_equivalents_fy_h)
            net_debt_ebitda_denominator = np.array(ebitda_fy_h)
            
            net_debt_to_ebitda_hs.append(np.around(net_debt_ebitda_numerator/net_debt_ebitda_denominator, decimals=2).tolist())

            if trace:
                print (5)


                     
            fcf_yield = np.around((fcf_ttm_value / market_cap) * 100, decimals=2)
            fcf_yields.append(fcf_yield)
            fcf_yields_hs.append(np.around((np.array(fcf_h_5_yrs) / np.array(enterprise_value_fy_h) ) * 100, decimals=2).tolist())


            if trace:
                print (6)



            dil_shrs_outstand_fy_h = [x for x in dil_shrs_outstand_fy_h if x != 0]
            
            #  share dilution
            oldest = dil_shrs_outstand_fy_h[0]
            latest = dil_shrs_outstand_fy_h[-1]

            
            years = len(dil_shrs_outstand_fy_h) - 1
            annualized_share_change = (
                (latest / oldest) ** (1 / years)
            ) - 1


                   
            share_change_pcts.append(annualized_share_change)

            if trace:
                print (7)
                
            share_changes = []
            
            for i in range(1, len(dil_shrs_outstand_fy_h)):
                if dil_shrs_outstand_fy_h[i-1] != 0:
                    pct_change = (dil_shrs_outstand_fy_h[i] - dil_shrs_outstand_fy_h[i-1]) / dil_shrs_outstand_fy_h[i-1]
                    share_changes.append(pct_change)

            all_share_changes.append(share_changes)


            if trace:
                print (8)

            
            # dil_shrs_outstand_fy_hs.append(np.around(np.array(dil_shrs_outstand_fy_h), decimals=2).tolist())
            # share_buyback_fy_ratios.append(share_buyback_fy_ratio)

            
            fcf_p_share_ttms.append(round(fcf_p_share, 2))
            fcf_p_share_fy_hs.append(np.around(np.array(fcf_p_share_fy_h), decimals=2).tolist())


            if trace:
                print (9)

            
            current_ratio = current_assets / current_liabilities
            current_ratios.append(round(current_ratio, 2))

       
            ca = np.array(current_assets_fy_h)
            cl = np.array(current_liabilities_fy_h)
            cr = ca / cl
            current_ratios_hs.append(np.around(cr, decimals=2))

            if trace:
                print (10)
            
            
            ebit_fy_h = np.array(ebit_fy_h)
            interest_expense_on_debt_fy_h = np.abs(np.array(interest_expense_on_debt_fy_h))               
            interest_coverage = np.around((ebit_fy_h / interest_expense_on_debt_fy_h), decimals=2)

            def my_action(x):
                return min(x, 100)
            
            vfunc = np.vectorize(my_action)
            interest_coverage = vfunc(interest_coverage)
            
            interest_coverages.append(interest_coverage.tolist())


            dividends = []
            
            for i in range(min(len(dividend_payment_date_h),  len(dividend_amount_h))):
                dividends.append( { 'date': datetime.fromtimestamp(dividend_payment_date_h[i]).strftime("%Y-%m-%d"),  'amount': dividend_amount_h[i] } )
                
            dividend_payments.append(dividends)


            if trace:
                print (11)
            # 1. market value per share
            # mv_per_share = market_cap / shares_outstanding

            
            # 2. get earnings per share
            # got it above


        except Exception as e:
            print (f'Error 2 ticker: {ticker} {e}')

    
    # print (len(return_on_invested_capitals), len(return_on_invested_capital_fy_hs), len(current_ratios), len(current_ratios_hs), len(fcf_p_share_ttms), len(interest_coverages), len(all_share_changes), len(share_change_pcts))
    # print (len(free_cash_flow_fy_hs),len(total_revenue_fy_hs), len(enterprise_value_ebitda_ttms), len(enterprise_value_ebitda_fq_hs), len(operating_margin_ttms), len(operating_margin_fy_hs), len(ev_to_sales_currents))
    # print (len(pe_fy_hs), len(price_earnings_currents), len(fcf_yields), len(fcf_yields_hs), len(price_return_1ys), len(dividend_yield_recents), len(net_debt_to_ebitdas), len(net_debt_to_ebitda_hs), len(dividend_payout_ratio_fys))
    # print (len(eps_dilu_ttms),len(eps_dil_fy_hs), len(eps_frcst_next_fy), len(fcf_p_share_fy_hs), len(market_caps))
    
    df_2 = pd.DataFrame({
        'ticker': tickers, 
        # 'country': countries,
        'classification': classifications,
        "roic": return_on_invested_capitals,
        "roic_fy_h": return_on_invested_capital_fy_hs,        
        "current_ratio": current_ratios,
        "current_ratio_h": current_ratios_hs,        
        "fcf_p_share_ttm": fcf_p_share_ttms,        
        "interest_coverage": interest_coverages,
        "share_changes_last_5yrs": all_share_changes,
        "latest_share_change_pct": share_change_pcts,
        "fcf_fy_h": free_cash_flow_fy_hs,
        'total_revenue_fy_h': total_revenue_fy_hs,
        "ev_ebitda_ttm": enterprise_value_ebitda_ttms,
        "ev_ebitda": enterprise_value_ebitda_fq_hs,
        'operating_margin_ttm': operating_margin_ttms,
        "operating_margin_fy_h": operating_margin_fy_hs,
        "ev_to_sales_current": ev_to_sales_currents,
        "ev_to_sales_hs": ev_to_sales_hs,
        "pe_fy_h": pe_fy_hs,
        "pe_current": price_earnings_currents,
        'fcf_yield': fcf_yields,
        "fcf_yields_fy_h": fcf_yields_hs,
        'price_return_1y': price_return_1ys,
        "dividend_yield_recent": dividend_yield_recents,        
        'net_debt_to_ebitda': net_debt_to_ebitdas,
        "net_debt_to_ebitda_hs": net_debt_to_ebitda_hs,
        "dividend_payout_ratio_fy": dividend_payout_ratio_fys,
        "dividend_payout_ratio_fy_h": dividend_payout_ratio_fy_hs,        
        "eps_dilu_ttms": eps_dilu_ttms,
        "eps_dil_fy_hs": eps_dil_fy_hs,
        "eps_frcst_next_fy": eps_frcst_next_fy,
        "fcf_p_share_fy_h": fcf_p_share_fy_hs,
        "market_cap" : market_caps,
        "dividend_payments": dividend_payments
    })

        # "dil_shares_outst": dil_shrs_outstand_fy_hs,
        # "buyback_ratio": share_buyback_fy_ratios,

    
    df_2.set_index('ticker', inplace=True)
    dict_2 = df_2.to_dict(orient='index')
    # df_2.to_json(PATH + 'technology.json')

    return df_2, dict_2

In [18]:
df_3, dict_3 = get_formatted_data(energy, False)
df_3[df_3['classification'] == 'integrated'][["ev_to_sales_hs"]]

Error in get_jsondata_from_file opening file for BP [Errno 2] No such file or directory: 'D:/Udemy/2026-Python3-ErikBanas/Section53_PythonForFinance/redo/dividends/BP.json'

                        ev_to_sales_hs
ticker
CNQ     [2.62, 2.32, 2.96, 3.23, 3.01]
COP      [2.41, 2.02, 2.73, 2.5, 2.29]
CVE      [0.97, 0.9, 0.97, 0.89, 1.08]
CVX     [1.63, 1.51, 1.52, 1.48, 1.78]
E         [0.84, 0.5, 0.81, 0.78, 1.0]
OXY     [2.51, 2.56, 3.01, 3.63, 3.31]
SHEL    [0.86, 0.69, 0.89, 0.87, 1.03]
TTE     [0.95, 0.68, 0.83, 0.81, 0.94]
XOM     [1.12, 1.22, 1.29, 1.45, 1.74]

In [34]:
def evaluate_energy_stocks(tickers, data, metrics):
    
    def normalize(score, max_score):
        if max_score <= 0:
            return 0.0
        # If your scoring system allows negative penalties, 
        # map them correctly so penalties aren't instantly wiped to 0.0
        return round(max(min(score / max_score, 1.0), -1.0), 2)
        
    def percentile_rank(values, x):
        values = sorted(v for v in values if v is not None)
        if not values:
            return None
        return sum(v <= x for v in values) / len(values)

    def trend_slope(values):

        if values is None or len(values) < 3:
            return None

        try:
            x = np.arange(len(values))
            slope = np.polyfit(x, values, 1)[0]
            return slope

        except:
            return None
            
    
    def improving(values, threshold=0.05):
    
        slope = trend_slope(values)
    
        if slope is None:
            return False
    
        return (
            slope > threshold and
            values[-1] > values[0]
        )
    
    def deteriorating(values, threshold=-0.05):
    
        slope = trend_slope(values)
    
        if slope is None:
            return False
    
        return slope < threshold
    
    def score_percentile(p, max_score=4, low_penalty=-1, severe_penalty=-2):
        score = 0
        text = None
        p = round(p, 3)
        if p >= 0.90:
            score =  max_score
            text = f"Great ({p})"
        elif p >= 0.75:
            score =  max_score - 1
            text = f"Attractive ({p})"
        elif p >= 0.50:
            score = max_score - 2
            text = f"Good ({p})"
        elif p >= 0.30:
            score = 1
            text = f"Fair ({p})"
        elif p < 0.10:
            score = severe_penalty
            text = f"Poor ({p})"
        else:
            score = low_penalty
            text = f"Neutral ({p})"

        return score, text

        
    def trend_improving(values, higher_is_better=True):
        try:
            
            if not values or len(values) < 2:
                return False
    
            if higher_is_better:
                return values[-1] > values[0]
            else:
                return values[-1] < values[0]
        except:
            print (f'Error in trend_improving {ticker} values: {values}')
            return None


    def weighted_slope(values):

        if values is None or len(values) < 3:
            return None
    
        try:
    
            y = np.array(values, dtype=float)
    
            # x-axis
            x = np.arange(len(y))
    
            # Increasing weights toward recent data
            weights = np.arange(1, len(y) + 1)
    
            slope = np.polyfit(x, y, 1, w=weights)[0]
    
            return slope
        except:
            return None

        
    def count_pos(ticker, values):
        try:
        
            return sum([1 for x in values if x > 0])
        except Exception:
            print (f' Error in count_pos {ticker}')

    
    results = {}



    UPSTREAM_WEIGHTS = {
        "valuation": 0.18,
        "profitability": 0.18,
        "quality": 0.17,
        "trend": 0.07,
        "growth": 0.03,
        "net_debt_to_ebitda": 0.07,
        "dividend_yield_recent": 0.025,
        "dividend_payout": 0.025,
        "ev_to_ebitda": .03,
        "fcf_yield": 0.19,
        "blue_chip": 0.03
    }

    MIDSTREAM_WEIGHTS = {
        "valuation": 0.15,
        "profitability": 0.15,
        "fcf_yield": 0.13,
        "trend": 0.03,
        "growth": 0.01,
        "net_debt_to_ebitda": 0.18,
        "dividend_yield_recent": 0.08,
        "dividend_payout": 0.05,
        "ev_to_ebitda": .03,
        "quality": 0.14,
        "blue_chip": 0.05
    }

    
    REFINING_WEIGHTS = {
        "valuation": 0.22,
        "profitability": 0.21,
        "quality": 0.12,
        "trend": 0.08,
        "growth": 0.03,
        "net_debt_to_ebitda": 0.06,
        "dividend_yield_recent": 0.03,
        "dividend_payout": 0.02,
        "ev_to_ebitda": .03,
        "fcf_yield": 0.18,
        "blue_chip": 0.02
    }
    

    OIL_SERVICES_WEIGHTS = {
        "profitability": 0.20,
        "fcf_yield": 0.16,
        "quality": 0.12,
        "trend": 0.12,
        "growth": 0.10,
        "net_debt_to_ebitda": 0.06,
        "dividend_yield_recent": 0.02,
        "dividend_payout": 0.02,
        "ev_to_ebitda": .03,
        "valuation": 0.15,
        "blue_chip": 0.02
    }

    
    INTEGRATED_WEIGHTS = {
        "valuation": 0.14,
        "profitability": 0.16,
        "fcf_yield": 0.18,
        "trend": 0.04,
        "growth": 0.01,
        "net_debt_to_ebitda": 0.08,
        "dividend_yield_recent": 0.03,
        "dividend_payout": 0.03,
        "ev_to_ebitda": 0.03,
        "quality": 0.22,
        "blue_chip": 0.08
    }
    

    DEFAULT_ENERGY_WEIGHTS = {
        "valuation": 0.18,
        "profitability": 0.18,
        "quality": 0.18,
        "trend": 0.07,
        "growth": 0.03,
        "net_debt_to_ebitda": 0.07,
        "dividend_yield_recent": 0.025,
        "dividend_payout": 0.025,
        "ev_to_ebitda": .03,
        "fcf_yield": 0.20,
        "blue_chip": 0.01
    }

    LOW_RISK_COUNTRIES = ["US", "NO", "CA"]
    HIGH_RISK_COUNTRIES = [
        "KZ",
        "CN",
        "RS",
        "BR"
    ]

    
    # VALUATION_MAX = 5
    # QUALITY_MAX = 25
    # TREND_MAX = 15
    # GROWTH_MAX = 3
    # PROFITABILITY_MAX = 4
    # FCF_YIELD_MAX = 5
    # NET_DEBT_TO_EBITDA_MAX = 4
    # DIVIDEND_YIELD_RECENT_MAX = 3
    # DIVIDEND_PAYOUT_RATIO_MAX = 1
    # EV_TO_EBITDA_MAX = 2
    # BLUE_CHIP_MAX = 6


    
    MIN_UNIVERSE_SIZE = 5

    
    
    metric_universes = defaultdict(lambda: defaultdict(list))

    all_roic_values = [data[t]["roic"] for t in tickers if data[t].get("roic") is not None]
    all_current_ratios = [data[t]["current_ratio"] for t in tickers if data[t].get("current_ratio") is not None]
    all_fcf_p_share_ttm = [data[t]["fcf_p_share_ttm"] for t in tickers if data[t].get("fcf_p_share_ttm") is not None]
    all_interest_coverage = [data[t]["interest_coverage"][-1] for t in tickers if data[t].get("interest_coverage") is not None]
    all_buyback_ratios = [data[t]["latest_share_change_pct"] for t in tickers if data[t].get("latest_share_change_pct") is not None]

    fcf_fy_h = [(t, data[t]["fcf_fy_h"]) for t in tickers if data[t].get("fcf_fy_h") is not None]
    all_pos_fcf_years = [count_pos(row[0], row[1]) for row in fcf_fy_h]
    
    all_growth_values = [get_growth_rates(data[t].get("total_revenue_fy_h", []))[-1] for t in tickers if get_growth_rates(data[t].get("total_revenue_fy_h", []))]
    all_ev_to_ebitda =  [data[t]["ev_ebitda_ttm"] for t in tickers if data[t].get("ev_ebitda_ttm") is not None]    
    all_operating_margin_values = [data[t]["operating_margin_ttm"] for t in tickers if data[t].get("operating_margin_ttm") is not None]
    all_ev_sales = [data[t]["ev_to_sales_current"] for t in tickers if data[t].get("ev_to_sales_current") is not None]
    all_pe_currents =  [data[t]["pe_current"] for t in tickers if data[t].get("pe_current") is not None]
    all_fcf_yields = [data[t]["fcf_yield"] for t in tickers if data[t].get("fcf_yield") is not None]    
    all_dividend_yields =  [data[t]["dividend_yield_recent"] for t in tickers if data[t].get("dividend_yield_recent") is not None]
    all_dividend_payout_ratios = [data[t]["dividend_payout_ratio_fy"] for t in tickers if data[t].get("dividend_payout_ratio_fy") is not None]
    all_net_debt_ebitda = [data[t]["net_debt_to_ebitda"] for t in tickers if data[t].get("net_debt_to_ebitda") is not None]

    
    
    # create universes of metrics for percentile comparison
    #  -------------------------------------------------------------------
    
    for ticker in tickers:
    
        # if ticker not in test_tickers:
        #     continue
            
        d = data.get(ticker, {})
        classification = d.get("classification")
        
        if not classification or classification is None:
            raise Exception("Missing classification")

        roic = d.get("roic")
        if roic is not None:
            metric_universes[classification]["roic"].append(roic)
        
        fcf_yield = d.get("fcf_yield")
        if fcf_yield is not None:
            metric_universes[classification]["fcf_yield"].append(fcf_yield)

        op_margin = d.get("operating_margin_ttm")
        if op_margin is not None:
            metric_universes[classification]["op_margin"].append(op_margin)

        debt = d.get("net_debt_to_ebitda")
        if debt is not None:
            metric_universes[classification]["net_debt_to_ebitda"].append(debt)

        current_ratio = d.get("current_ratio")
        if current_ratio is not None:
            metric_universes[classification]["current_ratio"].append(current_ratio)
        
        interest_coverage =  d.get('interest_coverage')
        if interest_coverage:
            interest_coverage = interest_coverage[-1]
            metric_universes[classification]["interest_coverage"].append(interest_coverage)
        
        fcf_p_share = d.get('fcf_p_share_ttm')
        if fcf_p_share is not None:
            metric_universes[classification]["fcf_p_share"].append(fcf_p_share)


        buyback_ratio = d.get('latest_share_change_pct')  
        if buyback_ratio is not None:
            metric_universes[classification]["buyback_ratio"].append(buyback_ratio)

        fcf = d.get("fcf_fy_h")
        if fcf is not None:
            metric_universes[classification]["fcf_pos_years"].append(count_pos(ticker, d.get("fcf_fy_h")))


        ev_to_sales_current = d.get('ev_to_sales_current')
        if  ev_to_sales_current is not None:
            metric_universes[classification]["ev_to_sales_current"].append(ev_to_sales_current)

        ev_ebitda_ttm = d.get('ev_ebitda_ttm')
        if  ev_ebitda_ttm is not None:
            metric_universes[classification]["ev_ebitda_ttm"].append(ev_ebitda_ttm)

        pe_current = d.get('pe_current')
        if  pe_current is not None:
            metric_universes[classification]["pe_current"].append(pe_current)

        revenues = d.get("total_revenue_fy_h")
        growths = get_growth_rates(revenues)
        if growths:
            metric_universes[classification]["revenue_growth"].append(growths[-1])

        # dividend_payout_ratio = d.get('dividend_payout_ratio_fy')
        # if dividend_payout_ratio is not None:
        #     metric_universes[classification]["dividend_payout_ratio"].append(dividend_payout_ratio)
            
        # if ticker not in test_tickers:
        #     continue

    
    
    #  -------------------------------------------------------------------
    # Start scoring
    #  -------------------------------------------------------------------
    
    max_bc = 0
    
    for ticker in tickers:


        QUALITY_MAX = 0
        TREND_MAX = 0
        GROWTH_MAX = 0
        VALUATION_MAX = 0
        EV_TO_EBITDA_MAX = 0
        PROFITABILITY_MAX = 0
        FCF_YIELD_MAX = 0
        DIVIDEND_YIELD_RECENT_MAX  = 0
        NET_DEBT_TO_EBITDA_MAX = 0
        DIVIDEND_YIELD_RECENT_MAX = 0
        DIVIDEND_PAYOUT_RATIO_MAX = 0
        BLUE_CHIP_MAX = 0
        
        final_score = 0
        reasons = []
        valuation_score = 0
        growth_score = 0
        profitability_score = 0
        trend_score = 0
        quality_score = 0
        fcf_yield_score = 0
        net_debt_to_ebitda_score = 0
        dividend_yield_recent_score = 0
        dividend_payout_score = 0
        ev_to_ebitda_score = 0
        blue_chip_score = 0

        growth = None
        fcf_yield = None
        price_return_1y = None
        
        d = data.get(ticker, {})

        classification = d.get("classification")

        if not classification or classification is None:
            raise Exception("Something went wrong!")
        
            
        roic_series = d.get("roic_fy_h", [])
        fcf_per_shares_series =  d.get("fcf_p_share_fy_h", [])
        interest_coverage_series = d.get("interest_coverage", [])
        current_ratio_h_series = d.get("current_ratio_h", [])
        share_changes_last_5yrs_series = d.get("share_changes_last_5yrs", [])
        ev_ebitda_series = d.get("ev_ebitda", [])
        op_margin_series = d.get("operating_margin_fy_h", [])
        ev_sales_series = d.get("ev_to_sales_hs", [])
        pe_series = d.get("pe_fy_h", [])
        fcf_yield_series = d.get("fcf_yields_fy_h", [])
        net_debt_to_ebitda_series = d.get("net_debt_to_ebitda_hs", [])
        dividend_payout_ratio_series = d.get("dividend_payout_ratio_fy_h", [])
        eps_series = d.get("eps_dil_fy_hs", [])
        dil_shares_outst_series = d.get("dil_shares_outst", [])
       

        # ---------------------------------------------------------------
        # 1. VALUATION
        
        if metrics.get("ev_to_sales") == True:
            
            VALUATION_MAX += 2
            ev_sales = d.get('ev_to_sales_current')

            
                 
            if ev_sales is not None:
    
                ev_sales_universe = metric_universes[classification]["ev_to_sales_current"]
                
                if len(ev_sales_universe) >= MIN_UNIVERSE_SIZE:
                    percentile = percentile_rank(ev_sales_universe, ev_sales)
                else:
                    percentile = percentile_rank(all_ev_sales, ev_sales)

                adjusted_percentile = 1 - percentile
                _, text = score_percentile(adjusted_percentile, max_score=2, low_penalty=-1, severe_penalty=-2)

                
                    
                score = ((adjusted_percentile * 2) - 1) * 4
                score = max(min(score, 2), -2)
                valuation_score += score

                if ticker == 'CVX':
                    print ('ev_sales',ev_sales)
                    print ('adjusted_percentile', adjusted_percentile)
                    print('score',score)
                    
                
                reasons.append(f"{text} EV/Sales")
        

        if metrics.get("pe") == True:
 
            VALUATION_MAX += 3
            pe_current = d.get('pe_current')
            
            if pe_current is not None and pe_current > 0:
    
                pe_universe = metric_universes[classification]["pe_current"]
    
                if len(pe_universe) >= MIN_UNIVERSE_SIZE:
                    percentile = percentile_rank(pe_universe, pe_current)
                else:
                    percentile = percentile_rank(all_pe_currents, pe_current)
                    
                
                adjusted_percentile = 1 - percentile
                score, text = score_percentile(adjusted_percentile, max_score=3, low_penalty=-1, severe_penalty=-2)
                valuation_score += score
                reasons.append(f"{text} P/E")


        
        # ---------------------------------------------------------------
        # 2. PROFITABILITY
        
        if metrics.get("op_margin") == True:
            PROFITABILITY_MAX += 4
            
            current_op_margin = d.get("operating_margin_ttm")
            
            if current_op_margin is not None:
    
                op_margin_universe = metric_universes[classification]["op_margin"]
                median_margin = np.median(op_margin_series[-5:])
                normalized_margin = current_op_margin * 0.6 + median_margin * 0.4
                
                if len(op_margin_universe) >= MIN_UNIVERSE_SIZE:
                    percentile = percentile_rank(op_margin_universe, normalized_margin)
                else:
                    percentile = percentile_rank(all_operating_margin_values, normalized_margin)
                    
                _, text = score_percentile(percentile, max_score=4, low_penalty=-1, severe_penalty=-2)
                
                score = ((percentile * 2) - 1) * 4
                score = max(min(score, 4), -4)
                profitability_score += score
                
                reasons.append(f"{text} Opr Margn")

        
        # ---------------------------------------------------------------
        # 3. QUALITY
        
        if metrics.get("roic") == True:
            QUALITY_MAX += 4
            
            current_roic = d.get("roic")
            
            if current_roic is not None:
                
                roic_universe = metric_universes[classification]["roic"]

                median_roic = np.median(roic_series)
                normalized_roic = current_roic * 0.6 + median_roic * 0.4
                
                if len(roic_universe) >= MIN_UNIVERSE_SIZE:
                    percentile = percentile_rank(roic_universe, current_roic)
                else:
                    percentile = percentile_rank(all_roic_values, current_roic)
    
                _, text = score_percentile(percentile, max_score=4, low_penalty=-1, severe_penalty=-2)
                
                    
                score = ((percentile * 2) - 1) * 4
                score = max(min(score, 4), -4)
                quality_score += score

                reasons.append(f"{text} ROIC") 

        
        if metrics.get("interest_coverage") == True:
            
            QUALITY_MAX += 4
            interest_coverage = interest_coverage_series[-1] if interest_coverage_series else None
               
            if interest_coverage is not None:
                
                interest_coverage_universe = metric_universes[classification]["interest_coverage"]
                if len(interest_coverage_universe) >= MIN_UNIVERSE_SIZE:
                    percentile = percentile_rank(interest_coverage_universe, interest_coverage)
                else:
                    percentile = percentile_rank(all_interest_coverage, interest_coverage)
                    
                _, text = score_percentile(percentile, max_score=4, low_penalty=-1, severe_penalty=-2)
    
                score = ((percentile * 2) - 1) * 4
                score = max(min(score, 4), -4)       
                quality_score += score
                
                reasons.append(f"{text} Interest Coverage")

        
        if metrics.get("current_ratio") == True:
            
            QUALITY_MAX += 4
            current_ratio = d.get('current_ratio')
            
            if current_ratio is not None:
    
                current_ratio = min(current_ratio, 3.0)
                current_ratio_universe = metric_universes[classification]["current_ratio"]
                
                if len(current_ratio_universe) >= MIN_UNIVERSE_SIZE:
                    percentile = percentile_rank(current_ratio_universe, current_ratio)
                else:
                    percentile = percentile_rank(all_current_ratios, current_ratio)
                    
                score, text = score_percentile(percentile, max_score=4, low_penalty=-1, severe_penalty=-2)
                quality_score += score
                
                # current_ratio_score = ((percentile * 2) - 1) * 4
                # current_ratio_score = max(min(current_ratio_score, 4), -4)       
                # quality_score += current_ratio_score            
    
                reasons.append(f"{text} Current Ratio") 

        
        if metrics.get("fcf_p_share") == True:
            
            QUALITY_MAX += 4
            fcf_p_share = d.get('fcf_p_share_ttm')        
                    
            if fcf_p_share is not None:
    
                fcf_p_share_universe = metric_universes[classification]["fcf_p_share"]
    
                if len(fcf_p_share_universe) >= MIN_UNIVERSE_SIZE:
                    percentile = percentile_rank(fcf_p_share_universe, fcf_p_share)
                else:
                    percentile = percentile_rank(all_fcf_p_share_ttm, fcf_p_share)

                _, text = score_percentile(percentile, max_score=4, low_penalty=-1, severe_penalty=-2)
    
                fcf_p_share_score = ((percentile * 2) - 1) * 4
                fcf_p_share_score = max(min(fcf_p_share_score, 4), -4)       
                quality_score += fcf_p_share_score            
                
                reasons.append(f"{text} FCF/Share") 

        
        if metrics.get("buyback_ratio") == True:
            
            QUALITY_MAX += 2
            buyback_ratio = d.get('latest_share_change_pct')
            
            if buyback_ratio is not None:
                buyback_universe = metric_universes[classification]["buyback_ratio"]

                if len(buyback_universe) >= MIN_UNIVERSE_SIZE:
                    percentile = percentile_rank(buyback_universe, buyback_ratio)
                else:
                    percentile = percentile_rank(all_buyback_ratios, buyback_ratio)

                percentile = round(percentile, 3)
                buyback_score = ((percentile * 2) - 1) * 2
                buyback_score = max(min(buyback_score, 2), -2)
            
                quality_score += buyback_score
       
            
                if buyback_score >= 1.5:
                    reasons.append(f"Aggressive {percentile} buyback")
                elif buyback_score >= 0.75:
                    reasons.append(f"Strong {percentile} shr. buyback")
                elif buyback_score > -0.75:
                    reasons.append(f"Average {percentile} shr. buyback")
                else:
                    reasons.append(f"Poor {percentile} shr. buyback")          

        
        if metrics.get("fcf_h") == True:
            
            QUALITY_MAX += 6
            free_cash_flow_fy_h = d.get('fcf_fy_h')

            if free_cash_flow_fy_h is not None:        

                score_consec, years_consecutive = get_blue_chip_score_for_consecutive_years(free_cash_flow_fy_h)
                quality_score += score_consec
                reasons.append(f'{years_consecutive} Year Streak Pos. FCF') 
                
                fcf_pos_years_universe = metric_universes[classification]["fcf_pos_years"]
                fcf_pos_years_count = count_pos(ticker, free_cash_flow_fy_h)
                                
                if len(fcf_pos_years_universe) >= MIN_UNIVERSE_SIZE:
                    percentile = percentile_rank(fcf_pos_years_universe, fcf_pos_years_count)
                else:
                    percentile = percentile_rank(all_pos_fcf_years, fcf_pos_years_count)
                    


                score, text = score_percentile(percentile, max_score=3, low_penalty=-1, severe_penalty=-2) 
                quality_score += score
                reasons.append(f'{text} Pos. Years FCF') 

        

        # ---------------------------------------------------------------
        # 4. GROWTH
        
        if metrics.get("rev_growth") == True:
            GROWTH_MAX += 3
           
            revenues = d.get("total_revenue_fy_h")
            
            if revenues is not None:

                growth_rates = get_growth_rates(revenues)
                current_growth = growth_rates[-1] if growth_rates else None

                if current_growth is not None:
                
                    growth_universe = metric_universes[classification]["revenue_growth"]

                    median_growth = np.median(growth_rates)
                    normalized_growth = current_growth * 0.6 + median_growth * 0.4
                
        
                    if len(growth_universe) >= MIN_UNIVERSE_SIZE:
                        percentile = percentile_rank(growth_universe, current_growth)
                    else:
                        percentile = percentile_rank(all_growth_values, current_growth)
                        
        
                    _, text = score_percentile(percentile, max_score=3, low_penalty=-1, severe_penalty=-2)     
        
                    score = ((percentile * 2) - 1) * 3
                    score = max(min(score, 3), -3)
                    growth_score += score
                    
                    reasons.append(f"{text} revenue growth")
        
        
        # ---------------------------------------------------------------  
        # 5. SPECIFIC SCORING

        if metrics.get("ev_to_ebitda") == True:
            EV_TO_EBITDA_MAX += 2
            
            ev_ebitda_ttm = d.get("ev_ebitda_ttm")
            
            if ev_ebitda_ttm is not None:
                
                ev_ebitda_universe = metric_universes[classification]["ev_ebitda_ttm"]
                universe = None
                if len(ev_ebitda_universe) >= MIN_UNIVERSE_SIZE:
                    universe = ev_ebitda_universe
                else:
                    universe = all_ev_to_ebitda

                universe = [x for x in universe if x > 0]
                universe = [min(x, 30) for x in universe]

                percentile = percentile_rank(universe, min(ev_ebitda_ttm, 30))
                
                adjusted_percentile = 1 - percentile
                _ , text = score_percentile(adjusted_percentile, max_score=2, low_penalty=0, severe_penalty=-1)
                score = ((adjusted_percentile * 2) - 1) * 2
                score = max(min(score, 2), -2)
                
                ev_to_ebitda_score += score
                
                reasons.append(f"**{text} EV/EBITDA TTM***")
        # ---------------------------------------------------------------     

        
        
        # ---------------------------------------------------------------
        if metrics.get("fcf_yield") == True:
            FCF_YIELD_MAX += 5
        
            current_fcf_yield = d.get("fcf_yield")
            
            if current_fcf_yield is not None:
    
                fcf_yield_universe = metric_universes[classification]["fcf_yield"]
                median_fcf_yield = np.median(fcf_yield_series[-5:])
                
                if not np.isn('median_fcf_yield'):
                    
                    normalized_fcf_yield = current_fcf_yield * 0.6 + median_fcf_yield * 0.4
                        
                    if len(fcf_yield_universe) >= MIN_UNIVERSE_SIZE:
                        percentile = percentile_rank(fcf_yield_universe, normalized_fcf_yield)
                    else:
                        percentile = percentile_rank(all_fcf_yields, normalized_fcf_yield)
                    
                    _, text = score_percentile(percentile, max_score=4, low_penalty=-1, severe_penalty=-2)
    
                    score = ((percentile * 2) - 1) * 4
                    score = max(min(score, 4), -4)
                    fcf_yield_score += score
                    reasons.append(f"{text} FCF Yield") 
        
                    if fcf_yield_series and min(fcf_yield_series[-3:]) > 0:
                        fcf_yield_score += 1
        # ---------------------------------------------------------------        


        
        # ---------------------------------------------------------------        
        if metrics.get("dy") == True:
            DIVIDEND_YIELD_RECENT_MAX += 3
            
            dividend_yield_recent = d.get("dividend_yield_recent")
            
            if dividend_yield_recent is not None:
    
                if dividend_yield_recent >= 12:  
                    dividend_yield_recent_score -= 2
                    reasons.append("High risk of dividend cut (Yield > 12%)")
                elif dividend_yield_recent >= 9: 
                    dividend_yield_recent_score += 1 
                    reasons.append("Very high yield; verify coverage ratio")
                elif dividend_yield_recent >= 6: 
                    dividend_yield_recent_score += 3 
                    reasons.append("Excellent Dividend Yield")
                elif dividend_yield_recent >= 4: 
                    dividend_yield_recent_score += 2 
                    reasons.append("Strong Dividend Yield")
                elif dividend_yield_recent >= 2: 
                    dividend_yield_recent_score += 1
                    reasons.append("Fair Dividend Yield")
                else:
                    dividend_yield_recent_score += 0
                    reasons.append("Low Dividend Yield")
        # ---------------------------------------------------------------        


                    
        # ---------------------------------------------------------------     
        if metrics.get("nd_ebit") == True:
            NET_DEBT_TO_EBITDA_MAX = 4
            
            net_debt_to_ebitda = d.get("net_debt_to_ebitda")        
            
            if net_debt_to_ebitda is not None:
    
                net_debt_to_ebitda_universe = metric_universes[classification]["net_debt_to_ebitda"]
    
                if len(net_debt_to_ebitda_universe) >= MIN_UNIVERSE_SIZE:
                    percentile = percentile_rank(net_debt_to_ebitda_universe, net_debt_to_ebitda)
                else:
                    percentile = percentile_rank(all_net_debt_ebitda, net_debt_to_ebitda)
                    
                adjusted_percentile = 1 - percentile
                _, text = score_percentile(adjusted_percentile, max_score=4, low_penalty=-1, severe_penalty=-3)

                score = ((adjusted_percentile * 2) - 1) * 4
                score = max(min(score, 4), -4)
                net_debt_to_ebitda_score += score

                reasons.append(f"{text} Net Debt / EBITDA")
        # ---------------------------------------------------------------        


        
        # ---------------------------------------------------------------        
        if metrics.get("div_payout") == True:
            DIVIDEND_PAYOUT_RATIO_MAX = 1
        
            dividend_payout_ratio_fy = d.get("dividend_payout_ratio_fy")
            
            if dividend_payout_ratio_fy is not None:
    
                if dividend_payout_ratio_fy < 50:
                    dividend_payout_score += 1
                    reasons.append("Healthy dividend payout")
                
                elif dividend_payout_ratio_fy <= 75:
                    dividend_payout_score += 0
                    reasons.append("Moderate dividend payout")
                
                elif dividend_payout_ratio_fy <= 90:
                    dividend_payout_score -= 1
                    reasons.append("Elevated dividend payout")
                
                elif dividend_payout_ratio_fy > 90:
                    dividend_payout_score -= 2
                    reasons.append("Unsustainable dividend payout")
        # ---------------------------------------------------------------        


        
        # ---------------------------------------------------------------   
        if metrics.get("bc") == True:
            BLUE_CHIP_MAX += 6
            
            market_cap = d.get("market_cap")
            if market_cap is not None:
                if market_cap > 300_000_000_000:
                    blue_chip_score += 2
                elif market_cap > 100_000_000_000:
                    blue_chip_score += 1
                    
            country = d.get('country')
            if country in LOW_RISK_COUNTRIES:
                blue_chip_score += 1


            
            dividend_payments = d.get("dividend_payments")
            
            if dividend_payments is not None:

                score = round(dividend_cagr(dividend_payments), 2)
                
                if score is not None:
                    if score >= 8:
                        blue_chip_score += 3
                        reasons.append(f"Excellent dividend growth {score}")
                    elif score >= 5:
                        blue_chip_score += 2
                        reasons.append(f"Strong dividend growth {score}")
                    elif score >= 2:
                        blue_chip_score += 1
                        reasons.append(f"Stable dividend growth {score}")
                    elif score < 0:
                        blue_chip_score -= 2
                        reasons.append(f"Dividend shrinking {score}")
        # ---------------------------------------------------------------        

        
        reasons.append('** TREND SCORING **')
        
        
        # ---------------------------------------------------------------        
        # 7.  Begin trend scoring
         
        if metrics.get("roic") == True:
            TREND_MAX += 1
            roic_last_3_years = roic_series[-3:]
            if deteriorating(roic_last_3_years, threshold=-.25):
                trend_score -= 1
                reasons.append("ROIC deteriorating")
            elif improving(roic_last_3_years, threshold=-.25):
                trend_score += 1
                reasons.append("ROIC improving")
            else:
                reasons.append("ROIC flat")


        if metrics.get("current_ratio") == True:
            current_ratio_slope = weighted_slope(current_ratio_h_series)
            TREND_MAX += .25
            if current_ratio_slope is not None:
                if current_ratio_slope > 0:
                    reasons.append("Current Ratio improv.")
                    trend_score += 0.25
                elif current_ratio_slope < 0:
                    trend_score -= 0.25
                    reasons.append("Current Ratio deter.")
                            

        if metrics.get("interest_coverage") == True:
            TREND_MAX += 1
            slope = weighted_slope(interest_coverage_series)

            latest_ic = interest_coverage_series[-1] if interest_coverage_series else None
            
            if improving(interest_coverage_series, threshold=0.25):
                reasons.append("Interest Cov. improving")
                trend_score += 1
            
            elif deteriorating(interest_coverage_series, threshold=-0.40):
            
                # Only penalize if coverage is already weak
                if latest_ic < 4:
                    reasons.append("Interest Cov. deteriorating")
                    trend_score -= 1
                else:
                    reasons.append("Interest Cov. still strong")
            
            else:
                reasons.append("Interest Cov. stable")
    
        
        if metrics.get("fcf_p_share") == True:
            TREND_MAX += 1
            if improving(fcf_per_shares_series, threshold=0.25):
                reasons.append("FCF/Share improving")            
                trend_score += 1        

        
        if metrics.get("buyback_ratio") == True:
            TREND_MAX += 1
            slope = round(weighted_slope(share_changes_last_5yrs_series), 2) if share_changes_last_5yrs_series else None
            if slope <= -0.02:
                trend_score += 1
                reasons.append("Strong share reduction")
            elif slope <= -0.005:
                trend_score += 0.5
                reasons.append("Improving share reduction")
            elif slope >= 0.02:
                trend_score -= 1
                reasons.append("Aggressive dilution")
            elif slope >= 0.005:
                trend_score -= 0.5
                reasons.append("Increasing dilution")
            

        # “Falling knife” penalty
        if metrics.get("pr1yr") == True:
            TREND_MAX += 2
            price_return_1y = d.get("price_return_1y")
            if price_return_1y is not None:
                if price_return_1y > 40:
                    trend_score += 2
                    reasons.append("Strong 1Y price momentum")
                elif price_return_1y > 15:
                    trend_score += 1
                    reasons.append("Positive 1Y price momentum")
                elif price_return_1y < -20:
                    trend_score -= 2
                    reasons.append("Weak 1Y price momentum")
                elif price_return_1y < 0:
                    trend_score -= 1
                    reasons.append("Negative 1Y price momentum")

            if (
                price_return_1y is not None and price_return_1y < -25
                and growth is not None and growth < 10
            ):
                trend_score -= 2
                reasons.append("Weak momentum with slow growth")


        # "Cash Cow" Logic
        if metrics.get("fcf_yield") == True and metrics.get("eps") == True:
            TREND_MAX += 1
            if fcf_yield is not None and fcf_yield > 7:
                if not trend_improving(eps_series, True):
                    # Offset the EPS penalty if the cash flow is great
                    trend_score += 1 
                    reasons.append("Strong FCF offsetting EPS cyclicality")
        
        if metrics.get("op_margin") == True:        
            TREND_MAX += 1
            op_margins = op_margin_series[-5:]
            if improving(op_margins, threshold=.25):
                trend_score += 1
                reasons.append("Operating margin improving")
        

        if metrics.get("fcf_yield") == True:
            TREND_MAX += 1  
            fcf_yields = fcf_yield_series[-3:]
            if improving(fcf_yields, threshold=.5):
                trend_score += 1
                reasons.append("FCF Yield rising")
            
        
        if metrics.get("nd_ebit") == True:
            TREND_MAX += 1
            if deteriorating(net_debt_to_ebitda_series, threshold=-0.2):            
                trend_score += 1
                reasons.append("Net Debt to EBITDA decreasing")


        if metrics.get("div_payout") == True:
            TREND_MAX += 1            
            if deteriorating(dividend_payout_ratio_series, threshold=-0.2):            
                trend_score += 1
                reasons.append("Div. Payout decreasing")
        

        if metrics.get("ev_to_sales") == True:
            TREND_MAX += 1
            ev_sales_3yrs = ev_sales_series[-3:]
            if ticker == 'CVX':
                print ('ev_sales_3yrs',ev_sales_3yrs)
            if deteriorating(ev_sales_3yrs):
                trend_score += 1
                reasons.append("EV/Sales decreasing")

        if metrics.get("pe") == True:
            TREND_MAX += 1           
            if deteriorating(pe_series, threshold=-0.25):
                trend_score += 1
                reasons.append("P/E decreasing")

        if metrics.get("ev_to_ebitda") == True:
            TREND_MAX += 1
            if deteriorating(ev_ebitda_series, threshold=.25):
                trend_score += 1
                reasons.append("EV/EBITDA decreasing")
        

        if metrics.get("eps") == True:
            TREND_MAX += 2
            
            eps_ttm = d.get("eps_dilu_ttms")
            eps_forecast = d.get("eps_frcst_next_fy")
            eps = eps_series[-1] if eps_series else None
            
            if eps_ttm is not None:
                if eps_ttm > 0:
                    
                    if trend_improving(eps_series, True):
                        trend_score += 1
                        reasons.append("EPS improving")
                    elif eps_ttm > 1.00: # New: "The Blue Chip Buffer"
                        trend_score += 0.5
                        reasons.append("EPS dipping but remains robust per share")
                        
                    if eps is not None and eps_forecast is not None:
                        if eps_forecast > eps * 1.15:
                            trend_score += 1
                            reasons.append("Strong forecasted EPS growth")
                        elif eps_forecast < eps * 0.85:
                            trend_score -= 1
                            reasons.append("Forecasted EPS decline")

        WEIGHTS = DEFAULT_ENERGY_WEIGHTS
        
        if classification == "upstream":
            WEIGHTS = UPSTREAM_WEIGHTS
        elif classification == "midstream":
            WEIGHTS = MIDSTREAM_WEIGHTS
        elif classification == "refining":
            WEIGHTS = REFINING_WEIGHTS
        elif classification == "oil_services":
            WEIGHTS = OIL_SERVICES_WEIGHTS
        elif classification == "integrated":
            WEIGHTS = INTEGRATED_WEIGHTS

        normalized_valuation = normalize(valuation_score, VALUATION_MAX) if VALUATION_MAX > 0 else 0
        normalized_growth = normalize(growth_score, GROWTH_MAX) if GROWTH_MAX > 0 else 0
        normalized_profitability = normalize(profitability_score, PROFITABILITY_MAX) if PROFITABILITY_MAX > 0 else 0
        normalized_quality = normalize(quality_score, QUALITY_MAX) if QUALITY_MAX > 0 else 0
        normalized_ev_to_ebitda = normalize(ev_to_ebitda_score, EV_TO_EBITDA_MAX) if EV_TO_EBITDA_MAX > 0 else 0      
        normalized_fcf_yield = normalize(fcf_yield_score, FCF_YIELD_MAX) if FCF_YIELD_MAX > 0 else 0
        normalized_dividend_yield_recent = normalize(dividend_yield_recent_score, DIVIDEND_YIELD_RECENT_MAX) if DIVIDEND_YIELD_RECENT_MAX > 0 else 0
        normalized_net_debt_to_ebitda = normalize(net_debt_to_ebitda_score, NET_DEBT_TO_EBITDA_MAX) if NET_DEBT_TO_EBITDA_MAX > 0 else 0
        normalized_dividend_payout = normalize(dividend_payout_score, DIVIDEND_PAYOUT_RATIO_MAX) if DIVIDEND_PAYOUT_RATIO_MAX > 0 else 0
        normalized_trend = normalize(trend_score, TREND_MAX) if TREND_MAX > 0 else 0
        normalized_blue_chip = normalize(blue_chip_score, BLUE_CHIP_MAX) if BLUE_CHIP_MAX > 0 else 0

        if ticker == 'CVX':
            print ('valuation_score',valuation_score)
            print ('VALUATION_MAX', VALUATION_MAX)
            print ('normalized_valuation',normalized_valuation)
            print ('WEIGHTS["valuation"]', WEIGHTS["valuation"])
            print (normalized_valuation  * WEIGHTS["valuation"])
            
        final_score = ((normalized_quality * WEIGHTS["quality"]) +
                        (normalized_trend * WEIGHTS["trend"]) +
                        (normalized_growth * WEIGHTS["growth"]) +
                        (normalized_profitability * WEIGHTS["profitability"]) +
                        (normalized_valuation * WEIGHTS["valuation"]) +
                        (normalized_ev_to_ebitda * WEIGHTS['ev_to_ebitda']) +
                        (normalized_dividend_yield_recent * WEIGHTS['dividend_yield_recent']) +
                        (normalized_net_debt_to_ebitda * WEIGHTS['net_debt_to_ebitda']) +
                        (normalized_dividend_payout * WEIGHTS['dividend_payout']) + 
                        (normalized_fcf_yield * WEIGHTS['fcf_yield']) +
                        (normalized_blue_chip * WEIGHTS['blue_chip']))
        
   
        final_score = round(final_score, 2)

        # Decision Engine
        if final_score >= 0.40:
            rating = "SB"
        elif final_score >= 0.30:
            rating = "BUY"
        elif final_score >= 0.20:
            rating = "HOLD"
        elif final_score >= 0.10:
            rating = "AVOID"
        else:
            rating = "SELL"

        if ticker == 'CVX':
            print ('final_score', final_score)
        
        results[ticker] = {
            "score": final_score,
            "rating": rating,
            "reasons": reasons,
            "classification": classification,
            "component_scores": {
                # "blue_chip_score": blue_chip_score,
                "valuation_score": valuation_score,
                "growth_score": growth_score,
                "profitability_score": profitability_score,
                "trend_score": trend_score,
                "quality_score": quality_score,
                "ev_to_ebitda_score": ev_to_ebitda_score,
                # "fcf_yield_score": fcf_yield_score,
                # "blue_chip_score": blue_chip_score,
                # "net_debt_to_ebitda_score": net_debt_to_ebitda_score,
                # "dividend_yield_recent_score": dividend_yield_recent_score,
                # "dividend_payout_score": dividend_payout_score,
                # "normalized_blue_chip": normalized_blue_chip,
                "normalized_valuation": normalized_valuation,
                "normalized_growth": normalized_growth,
                "normalized_profitability": normalized_profitability,
                "normalized_trend": normalized_trend,
                "normalized_quality": normalized_quality,
                "normalized_ev_to_ebitda": normalized_ev_to_ebitda,                
                # "normalized_fcf_yield": normalized_fcf_yield,
                # "normalized_net_debt_to_ebitda": normalized_net_debt_to_ebitda,
                # "normalized_dividend_yield_recent": normalized_dividend_yield_recent,
                # "normalized_dividend_payout": normalized_dividend_payout,
                # "weighted_blue_chip":  (normalized_blue_chip * WEIGHTS["blue_chip"]),
                "weighted_valuation":  (normalized_valuation * WEIGHTS["valuation"]),
                "weighted_growth": (normalized_growth * WEIGHTS["growth"]),
                "weighted_profitability": (normalized_profitability * WEIGHTS["profitability"]),
                "weighted_trend": (normalized_trend * WEIGHTS["trend"]),
                "weighted_quality": (normalized_quality * WEIGHTS["quality"]),
                "weighted_ev_ebitda": (normalized_ev_to_ebitda * WEIGHTS["ev_to_ebitda"]),
                # "weighted_fcf_yield": (normalized_fcf_yield * WEIGHTS['fcf_yield']),
                # "weighted_net_debt_to_ebitda": (normalized_net_debt_to_ebitda * WEIGHTS['net_debt_to_ebitda']),
                # "weighted_dividend_yield": (normalized_dividend_yield_recent * WEIGHTS['dividend_yield_recent']),
                # "weighted_dividend_payout": (normalized_dividend_payout * WEIGHTS['dividend_payout']),
            }
        }


    return results

In [35]:
df_3, dict_3 = get_formatted_data(energy, False)
metrics = { "roic": False, "interest_coverage": False,  "op_margin": False, "fcf_yield": False, "nd_ebit": False, "ev_to_ebitda": False, "rev_growth": False,
           "current_ratio": False, "fcf_p_share": False, "buyback_ratio": False, 
           "fcf_h": False,  "ev_to_sales": True, "pe": False, "pr1yr": False, "dy": False, "div_payout": False, "eps": False, "bc": False }
results = evaluate_energy_stocks(df_3.index.tolist(), dict_3, metrics)
df_6 = get_results_report(results)
mask = (df_6['class.'] == 'integrated')
df_6[mask].sort_values(by=['class.','score'], ascending=[True,False])

Error in get_jsondata_from_file opening file for BP [Errno 2] No such file or directory: 'D:/Udemy/2026-Python3-ErikBanas/Section53_PythonForFinance/redo/dividends/BP.json'
ev_sales 2.28
adjusted_percentile 0.33333333333333337
score -1.333333333333333
ev_sales_3yrs [1.52, 1.48, 1.78]
valuation_score -1.333333333333333
VALUATION_MAX 2
normalized_valuation -0.67
WEIGHTS["valuation"] 0.14
-0.09380000000000001
final_score -0.09

,rating,score,class.,reason
ticker,,,,
E,AVOID,0.14,integrated,"[Attractive (0.778) EV/Sales, ** TREND SCORING..."
SHEL,AVOID,0.14,integrated,"[Attractive (0.889) EV/Sales, ** TREND SCORING..."
TTE,SELL,0.09,integrated,"[Good (0.667) EV/Sales, ** TREND SCORING **]"
CVE,SELL,0.03,integrated,"[Good (0.556) EV/Sales, ** TREND SCORING **]"
XOM,SELL,-0.03,integrated,"[Fair (0.444) EV/Sales, ** TREND SCORING **]"
CVX,SELL,-0.09,integrated,"[Fair (0.333) EV/Sales, ** TREND SCORING **]"
COP,SELL,-0.10,integrated,"[Neutral (0.222) EV/Sales, ** TREND SCORING **..."
CNQ,SELL,-0.14,integrated,"[Poor (0.0) EV/Sales, ** TREND SCORING **]"
OXY,SELL,-0.14,integrated,"[Neutral (0.111) EV/Sales, ** TREND SCORING **]"

In [534]:
# df_3, dict_3 = get_formatted_data(energy, False)
# metrics = { "roic": True, "interest_coverage": True,  "op_margin": True, "fcf_yield": True, "nd_ebit": True, "ev_to_ebitda": True, "rev_growth": True,
#            "current_ratio": True, "fcf_p_share": True, "buyback_ratio": True, 
#            "fcf_h": True,  "ev_to_sales": True, "pe": True, "pr1yr": True, "dy": True, "div_payout": True, "eps": True, "bc": True }
# results = evaluate_energy_stocks(df_3.index.tolist(), dict_3, metrics)
# df_6 = get_results_report(results)
# mask = (df_6['class.'] == 'integrated')
# df_6[mask].sort_values(by=['class.','score'], ascending=[True,False])

Error in get_jsondata_from_file opening file for BP [Errno 2] No such file or directory: 'D:/Udemy/2026-Python3-ErikBanas/Section53_PythonForFinance/redo/dividends/BP.json'

In [29]:
df_3, dict_3 = get_formatted_data(energy, False)
metrics = { "roic": False, "interest_coverage": False,  "op_margin": False, "fcf_yield": False, "nd_ebit": False, "ev_to_ebitda": False, "rev_growth": False,
           "current_ratio": False, "fcf_p_share": False, "buyback_ratio": False, 
           "fcf_h": False,  "ev_to_sales": True, "pe": False, "pr1yr": False, "dy": False, "div_payout": False, "eps": False, "bc": False }
results = evaluate_energy_stocks2(df_3.index.tolist(), dict_3, metrics)
df_6 = get_results_report(results)
mask = (df_6['class.'] == 'integrated') #& (df_6.index == 'XOM')
df_6[mask].sort_values(by=['class.','score'], ascending=[True,False])

Error in get_jsondata_from_file opening file for BP [Errno 2] No such file or directory: 'D:/Udemy/2026-Python3-ErikBanas/Section53_PythonForFinance/redo/dividends/BP.json'
[4.1, 2.82, 1.82, 2.28, 1.21, 3.71, 1.12, 1.29, 2.11]
percentile 0.6666666666666666
adjusted percentile 0.33333333333333337
score 1
ev_to_sales_h [1.52, 1.48, 1.78]
CVX ---------
scores[m2] 1.0
safe_normalize(scores[key], max_bounds[key]) 0.5
norm_metrics[m2] 0.5
weights[m2] 0.14
trend score 0.0
quality score 0.07
final_score2 0.07

,rating,score,class.,reason
ticker,,,,
CVX,SELL,0.07,integrated,"[Fair (0.333) EV/Sales, ** TREND SCORING **]"
E,SELL,0.07,integrated,"[Attractive (0.778) EV/Sales, ** TREND SCORING..."
SHEL,SELL,0.07,integrated,"[Attractive (0.889) EV/Sales, ** TREND SCORING..."
XOM,SELL,0.07,integrated,"[Fair (0.444) EV/Sales, ** TREND SCORING **]"
CVE,SELL,0.00,integrated,"[Good (0.556) EV/Sales, ** TREND SCORING **]"
TTE,SELL,0.00,integrated,"[Good (0.667) EV/Sales, ** TREND SCORING **]"
COP,SELL,-0.03,integrated,"[Neutral (0.222) EV/Sales, ** TREND SCORING **..."
OXY,SELL,-0.07,integrated,"[Neutral (0.111) EV/Sales, ** TREND SCORING **]"
CNQ,SELL,-0.14,integrated,"[Poor (0.0) EV/Sales, ** TREND SCORING **]"

In [23]:
def evaluate_energy_stocks2(tickers, data, metrics):
    
    # --- HELPER FUNCTIONS ---
    def safe_normalize(score, max_score):
        if max_score <= 0:
            return 0.0
        # If your scoring system allows negative penalties, 
        # map them correctly so penalties aren't instantly wiped to 0.0
        return round(max(min(score / max_score, 1.0), -1.0), 2)
        
    def percentile_rank(universe_values, target_value):
        if not universe_values or target_value is None:
            return 0.0
        # Clean out None/NaN values safely
        cleaned = sorted([v for v in universe_values if v is not None and not np.isnan(v)])
        if not cleaned:
            return 0.0
        return sum(v <= target_value for v in cleaned) / len(cleaned)

    def trend_slope(values):
        if values is None or len(values) < 3:
            return None
        try:
            x = np.arange(len(values))
            return np.polyfit(x, values, 1)[0]
        except Exception:
            return None
    
    def improving(values, threshold=0.05):
        slope = trend_slope(values)
        return slope > threshold and values[-1] > values[0] if slope is not None else False
    
    def deteriorating(values, threshold=-0.05):
        slope = trend_slope(values)
        return slope < threshold if slope is not None else False
    
    def score_percentile(p, max_score=4, low_penalty=-1, severe_penalty=-2):
        p = round(p, 3)
        if p >= 0.90:
            return max_score, f"Great ({p})"
        if p >= 0.75:
            return max_score - 1, f"Attractive ({p})"
        if p >= 0.50:
            return max_score - 2, f"Good ({p})"
        if p >= 0.30:
            return 1, f"Fair ({p})"
        if p < 0.10:
            return severe_penalty, f"Poor ({p})"
            
        return low_penalty, f"Neutral ({p})"

    def trend_improving(ticker_symbol, values, higher_is_better=True):
        if not values or len(values) < 2:
            return False
        try:
            return values[-1] > values[0] if higher_is_better else values[-1] < values[0]
        except Exception as e:
            print(f"Error in trend_improving for {ticker_symbol}: {e}")
            return False

    def weighted_slope(values):
        if values is None or len(values) < 3:
            return None
        try:
            y = np.array(values, dtype=float)
            x = np.arange(len(y))
            weights = np.arange(1, len(y) + 1)
            return np.polyfit(x, y, 1, w=weights)[0]
        except Exception:
            return None
        
    def count_pos(ticker_symbol, values):
        try:
            return sum(1 for x in values if x is not None and x > 0)
        except Exception as e:
            print(f"Error in count_pos for {ticker_symbol}: {e}")
            return 0

    # --- WEIGHT CONFIGURATIONS ---
    SUBSECTOR_WEIGHTS = {
        "upstream": {"valuation": 0.18, "profitability": 0.18, "quality": 0.17, "trend": 0.07, "growth": 0.03, "net_debt_to_ebitda": 0.07, "dividend_yield_recent": 0.025, "dividend_payout": 0.025, "ev_to_ebitda": 0.03, "fcf_yield": 0.19, "blue_chip": 0.03},
        "midstream": {"valuation": 0.15, "profitability": 0.15, "fcf_yield": 0.13, "trend": 0.03, "growth": 0.01, "net_debt_to_ebitda": 0.18, "dividend_yield_recent": 0.08, "dividend_payout": 0.05, "ev_to_ebitda": 0.03, "quality": 0.14, "blue_chip": 0.05},
        "refining": {"valuation": 0.22, "profitability": 0.21, "quality": 0.12, "trend": 0.08, "growth": 0.03, "net_debt_to_ebitda": 0.06, "dividend_yield_recent": 0.03, "dividend_payout": 0.02, "ev_to_ebitda": 0.03, "fcf_yield": 0.18, "blue_chip": 0.02},
        "oil_services": {"profitability": 0.20, "fcf_yield": 0.16, "quality": 0.12, "trend": 0.12, "growth": 0.10, "net_debt_to_ebitda": 0.06, "dividend_yield_recent": 0.02, "dividend_payout": 0.02, "ev_to_ebitda": 0.03, "valuation": 0.15, "blue_chip": 0.02},
        "integrated": {"valuation": 0.14, "profitability": 0.16, "fcf_yield": 0.18, "trend": 0.04, "growth": 0.01, "net_debt_to_ebitda": 0.08, "dividend_yield_recent": 0.03, "dividend_payout": 0.03, "ev_to_ebitda": 0.03, "quality": 0.22, "blue_chip": 0.08},
        "default": {"valuation": 0.18, "profitability": 0.18, "quality": 0.18, "trend": 0.07, "growth": 0.03, "net_debt_to_ebitda": 0.07, "dividend_yield_recent": 0.025, "dividend_payout": 0.025, "ev_to_ebitda": 0.03, "fcf_yield": 0.20, "blue_chip": 0.01}
    }

    LOW_RISK_COUNTRIES = {"US", "NO", "CA"}
    MIN_UNIVERSE_SIZE = 5
    
    # --- UNIVERSE BUILDER ---
    metric_universes = defaultdict(lambda: defaultdict(list))
    global_universes = defaultdict(list)

    # Extract all metric environments cleanly in a single pass
    for t in tickers:
        d = data.get(t, {})
        cls = d.get("classification", "default")
        
        mapping = {
            "roic": d.get("roic"),
            "fcf_yield": d.get("fcf_yield"),
            "op_margin": d.get("operating_margin_ttm"),
            "net_debt_to_ebitda": d.get("net_debt_to_ebitda"),
            "current_ratio": d.get("current_ratio"),
            "fcf_p_share": d.get("fcf_p_share_ttm"),
            "buyback_ratio": d.get("latest_share_change_pct"),
            "ev_to_sales_current": d.get("ev_to_sales_current"),
            "ev_ebitda_ttm": d.get("ev_ebitda_ttm"),
            "pe_current": d.get("pe_current"),
            "interest_coverage": d.get("interest_coverage")[-1] if d.get("interest_coverage") else None,
            "fcf_pos_years": count_pos(t, d.get("fcf_fy_h", [])),
            "revenue_growth": get_growth_rates(d.get("total_revenue_fy_h", []))[-1] if d.get("total_revenue_fy_h") else None
        }
        
        for metric_name, val in mapping.items():
            if val is not None:
                metric_universes[cls][metric_name].append(val)
                global_universes[metric_name].append(val)

    print (metric_universes['integrated']['ev_to_sales_current'])
    
    # --- MAIN SCORING LOOP ---
    results = {}
    
    for ticker in tickers:
        d = data.get(ticker, {})
        cls = d.get("classification", "default")
        weights = SUBSECTOR_WEIGHTS.get(cls, SUBSECTOR_WEIGHTS["default"])
        
        # Initialize running counts & sub-scores
        max_bounds = defaultdict(int)
        scores = defaultdict(float)
        reasons = []

        # Helper to decide fallback strategy for percentiles
        def get_working_universe(metric_key):
            sub_uni = metric_universes[cls][metric_key]
            return sub_uni if len(sub_uni) >= MIN_UNIVERSE_SIZE else global_universes[metric_key]

        # 1. Valuation
        if metrics.get("ev_to_sales"):
            max_bounds["valuation"] += 2
            ev_sales = d.get("ev_to_sales_current")
            
            if ev_sales is not None:
                p = percentile_rank(get_working_universe("ev_to_sales_current"), ev_sales)
                score, text = score_percentile(1 - p, max_score=2)
                scores["valuation"] += score
                if ticker == 'CVX':
                    print ('percentile', p)
                    print ('adjusted percentile', 1 - p)
                    print ('score', score)
                    
                reasons.append(f"{text} EV/Sales")

        if metrics.get("pe"):
            max_bounds["valuation"] += 3
            pe_curr = d.get("pe_current")
            if pe_curr is not None and pe_curr > 0:
                p = percentile_rank(get_working_universe("pe_current"), pe_curr)
                score, text = score_percentile(1 - p, max_score=3)
                scores["valuation"] += score
                reasons.append(f"{text} P/E")

        # 2. Profitability
        if metrics.get("op_margin"):
            max_bounds["profitability"] += 4
            op_margin = d.get("operating_margin_ttm")
            if op_margin is not None:
                p = percentile_rank(get_working_universe("op_margin"), op_margin)
                _, text = score_percentile(p, max_score=4)
                score = max(min(((p * 2) - 1) * 4, 4), -4)
                scores["profitability"] += score
                reasons.append(f"{text} Opr Margn")

        # 3. Quality
        if metrics.get("roic"):
            max_bounds["quality"] += 4
            roic = d.get("roic")
            if roic is not None:
                p = percentile_rank(get_working_universe("roic"), roic)
                _, text = score_percentile(p, max_score=4)
                score = max(min(((p * 2) - 1) * 4, 4), -4)
                scores["quality"] += score
                reasons.append(f"{text} ROIC")

        if metrics.get("interest_coverage"):
            max_bounds["quality"] += 4
            ic_series = d.get("interest_coverage", [])
            ic_latest = ic_series[-1] if ic_series else None
            if ic_latest is not None:
                p = percentile_rank(get_working_universe("interest_coverage"), ic_latest)
                _, text = score_percentile(p, max_score=4)
                score = max(min(((p * 2) - 1) * 4, 4), -4)
                scores["quality"] += score
                reasons.append(f"{text} Interest Coverage")

        if metrics.get("current_ratio"):
            max_bounds["quality"] += 4
            cr = d.get("current_ratio")
            if cr is not None:
                p = percentile_rank(get_working_universe("current_ratio"), min(cr, 3.0))
                score, text = score_percentile(p, max_score=4)
                scores["quality"] += score
                reasons.append(f"{text} Current Ratio")

        if metrics.get("fcf_p_share"):
            max_bounds["quality"] += 4
            fcf_ps = d.get("fcf_p_share_ttm")
            if fcf_ps is not None:
                p = percentile_rank(get_working_universe("fcf_p_share"), fcf_ps)
                score, text = score_percentile(p, max_score=4)
                scores["quality"] += score
                reasons.append(f"{text} FCF/Share")

        if metrics.get("buyback_ratio"):
            max_bounds["quality"] += 2
            bb_ratio = d.get("latest_share_change_pct")
            if bb_ratio is not None:
                p = round(percentile_rank(get_working_universe("buyback_ratio"), bb_ratio), 3)
                score = max(min(((p * 2) - 1) * 2, 2), -2)
                scores["quality"] += score
                if score >= 1.5: reasons.append(f"Aggressive {p} buyback")
                elif score >= 0.75: reasons.append(f"Strong {p} shr. buyback")
                elif score > -0.75: reasons.append(f"Average {p} shr. buyback")
                else: reasons.append(f"Poor {p} shr. buyback")

        if metrics.get("fcf_h"):
            max_bounds["quality"] += 6
            fcf_h = d.get("fcf_fy_h", [])
            if fcf_h:
                # Note: assumed get_blue_chip_score_for_consecutive_years is defined globally environment-side
                score_consec, years_consecutive = get_blue_chip_score_for_consecutive_years(fcf_h)
                scores["quality"] += score_consec
                reasons.append(f"{years_consecutive} Year Streak Pos. FCF")
                
                fcf_count = count_pos(ticker, fcf_h)
                p = percentile_rank(get_working_universe("fcf_pos_years"), fcf_count)
                score, text = score_percentile(p, max_score=3)
                scores["quality"] += score
                reasons.append(f"{text} Pos. Years FCF")

        # 4. Growth
        rev_growth_rate = None
        if metrics.get("rev_growth"):
            max_bounds["growth"] += 3
            revenues = d.get("total_revenue_fy_h", [])
            growth_rates = get_growth_rates(revenues) if revenues else []
            if growth_rates:
                rev_growth_rate = growth_rates[-1]
                p = percentile_rank(get_working_universe("revenue_growth"), rev_growth_rate)
                _, text = score_percentile(p, max_score=3)
                score = max(min(((p * 2) - 1) * 3, 3), -3)
                scores["growth"] += score
                reasons.append(f"{text} revenue growth")

        # 5. Metric Specifics (EV/EBITDA, FCF Yield, Dividends, Debt)
        if metrics.get("ev_to_ebitda"):
            max_bounds["ev_to_ebitda"] += 2
            ev_ebitda = d.get("ev_ebitda_ttm")
            if ev_ebitda is not None:
                raw_uni = get_working_universe("ev_ebitda_ttm")
                clean_uni = [min(x, 30) for x in raw_uni if x > 0]
                p = percentile_rank(clean_uni, min(ev_ebitda, 30))
                _, text = score_percentile(1 - p, max_score=2, low_penalty=0, severe_penalty=-1)
                score = max(min((((1 - p) * 2) - 1) * 2, 2), -2)
                scores["ev_to_ebitda"] += score
                reasons.append(f"**{text} EV/EBITDA TTM***")

        if metrics.get("fcf_yield"):
            max_bounds["fcf_yield"] += 5
            fcf_y = d.get("fcf_yield")
            if fcf_y is not None:
                p = percentile_rank(get_working_universe("fcf_yield"), fcf_y)
                _, text = score_percentile(p, max_score=4)
                score = max(min(((p * 2) - 1) * 4, 4), -4)
                scores["fcf_yield"] += score
                reasons.append(f"{text} FCF Yield")
            
            fcf_y_series = d.get("fcf_yields_fy_h", [])
            if fcf_y_series and min(fcf_y_series) > 0:
                scores["fcf_yield"] += 1

        if metrics.get("dy"):
            max_bounds["dividend_yield_recent"] += 3
            dy_rec = d.get("dividend_yield_recent")
            if dy_rec is not None:
                if dy_rec >= 12:
                    scores["dividend_yield_recent"] -= 2
                    reasons.append("High risk of dividend cut (Yield > 12%)")
                elif dy_rec >= 9:
                    scores["dividend_yield_recent"] += 1
                    reasons.append("Very high yield; verify coverage ratio")
                elif dy_rec >= 6:
                    scores["dividend_yield_recent"] += 3
                    reasons.append("Excellent Dividend Yield")
                elif dy_rec >= 4:
                    scores["dividend_yield_recent"] += 2
                    reasons.append("Strong Dividend Yield")
                elif dy_rec >= 2:
                    scores["dividend_yield_recent"] += 1
                    reasons.append("Fair Dividend Yield")
                else:
                    reasons.append("Low Dividend Yield")

        if metrics.get("nd_ebit"):
            max_bounds["net_debt_to_ebitda"] += 4
            nd_ebitda = d.get("net_debt_to_ebitda")
            if nd_ebitda is not None:
                p = percentile_rank(get_working_universe("net_debt_to_ebitda"), nd_ebitda)
                _, text = score_percentile(1 - p, max_score=4, low_penalty=-1, severe_penalty=-3)
                score = max(min(((1 - p) * 2 - 1) * 4, 4), -4)
                scores["net_debt_to_ebitda"] += score
                reasons.append(f"{text} Net Debt / EBITDA")

        if metrics.get("div_payout"):
            max_bounds["dividend_payout"] += 1
            payout = d.get("dividend_payout_ratio_fy")
            if payout is not None:
                if payout < 50:
                    scores["dividend_payout"] += 1
                    reasons.append("Healthy dividend payout")
                elif payout <= 75:
                    reasons.append("Moderate dividend payout")
                elif payout <= 90:
                    scores["dividend_payout"] -= 1
                    reasons.append("Elevated dividend payout")
                else:
                    scores["dividend_payout"] -= 2
                    reasons.append("Unsustainable dividend payout")

        if metrics.get("bc"):
            max_bounds["blue_chip"] += 6
            mcap = d.get("market_cap", 0)
            if mcap > 300_000_000_000: scores["blue_chip"] += 2
            elif mcap > 100_000_000_000: scores["blue_chip"] += 1
            
            if d.get("country") in LOW_RISK_COUNTRIES:
                scores["blue_chip"] += 1

            div_payments = d.get("dividend_payments")
            if div_payments is not None:
                # Note: assumed dividend_cagr is defined globally environment-side
                bc_cagr = round(dividend_cagr(div_payments), 2)
                if bc_cagr is not None:
                    if bc_cagr >= 8:
                        scores["blue_chip"] += 3
                        reasons.append(f"Excellent dividend growth {bc_cagr}")
                    elif bc_cagr >= 5:
                        scores["blue_chip"] += 2
                        reasons.append(f"Strong dividend growth {bc_cagr}")
                    elif bc_cagr >= 2:
                        scores["blue_chip"] += 1
                        reasons.append(f"Stable dividend growth {bc_cagr}")
                    elif bc_cagr < 0:
                        scores["blue_chip"] -= 2
                        reasons.append(f"Dividend shrinking {bc_cagr}")

        # 6. Trend-specific Momentum Scoring
        reasons.append('** TREND SCORING **')
        
        if metrics.get("roic"):
            max_bounds["trend"] += 1
            roic_series = d.get("roic_fy_h", [])
            roic_last_3_years = roic_series[-3:]
            if deteriorating(roic_last_3_years, threshold=-0.25):
                scores["trend"] -= 1
                reasons.append("ROIC deteriorating")
            elif improving(roic_last_3_years, threshold=-0.25):
                scores["trend"] += 1
                reasons.append("ROIC improving")
            else:
                reasons.append("ROIC flat")

        if metrics.get("current_ratio"):
            max_bounds["trend"] += 0.25
            cr_slope = weighted_slope(d.get("current_ratio_h", []))
            if cr_slope is not None:
                if cr_slope > 0:
                    reasons.append("Current Ratio improv.")
                    scores["trend"] += 0.25
                elif cr_slope < 0:
                    scores["trend"] -= 0.25
                    reasons.append("Current Ratio deter.")

        if metrics.get("interest_coverage"):
            max_bounds["trend"] += 1
            ic_series = d.get("interest_coverage", [])
            ic_latest = ic_series[-1] if ic_series else None
            if improving(ic_series, threshold=0.25):
                reasons.append("Interest Cov. improving")
                scores["trend"] += 1
            elif deteriorating(ic_series, threshold=-0.40):
                if ic_latest is not None and ic_latest < 4:
                    reasons.append("Interest Cov. deteriorating")
                    scores["trend"] -= 1
                else:
                    reasons.append("Interest Cov. still strong")
            else:
                reasons.append("Interest Cov. stable")

        if metrics.get("fcf_p_share"):
            max_bounds["trend"] += 1
            if improving(d.get("fcf_p_share_fy_h", []), threshold=0.25):
                reasons.append("FCF/Share improving")            
                scores["trend"] += 1        

        if metrics.get("buyback_ratio"):
            max_bounds["trend"] += 1
            s_last_5 = d.get("share_changes_last_5yrs", [])
            w_slope = weighted_slope(s_last_5)
            slope = round(w_slope, 2) if w_slope is not None else None
            if slope is not None:
                if slope <= -0.02:
                    scores["trend"] += 1
                    reasons.append("Strong share reduction")
                elif slope <= -0.005:
                    scores["trend"] += 0.5
                    reasons.append("Improving share reduction")
                elif slope >= 0.02:
                    scores["trend"] -= 1
                    reasons.append("Aggressive dilution")
                elif slope >= 0.005:
                    scores["trend"] -= 0.5
                    reasons.append("Increasing dilution")

        if metrics.get("pr1yr"):
            max_bounds["trend"] += 2
            p_ret_1y = d.get("price_return_1y")
            if p_ret_1y is not None:
                if p_ret_1y > 40:
                    scores["trend"] += 2
                    reasons.append("Strong 1Y price momentum")
                elif p_ret_1y > 15:
                    scores["trend"] += 1
                    reasons.append("Positive 1Y price momentum")
                elif p_ret_1y < -20:
                    scores["trend"] -= 2
                    reasons.append("Weak 1Y price momentum")
                elif p_ret_1y < 0:
                    scores["trend"] -= 1
                    reasons.append("Negative 1Y price momentum")

                if p_ret_1y < -25 and rev_growth_rate is not None and rev_growth_rate < 10:
                    scores["trend"] -= 2
                    reasons.append("Weak momentum with slow growth")

        if metrics.get("fcf_yield") and metrics.get("eps"):
            max_bounds["trend"] += 1
            fcf_y = d.get("fcf_yield")
            if fcf_y is not None and fcf_y > 7:
                if not trend_improving(ticker, d.get("eps_dil_fy_hs", []), True):
                    scores["trend"] += 1 
                    reasons.append("Strong FCF offsetting EPS cyclicality")
        
        if metrics.get("op_margin"):        
            max_bounds["trend"] += 1
            if improving(d.get("operating_margin_fy_h", []), threshold=0.25):
                scores["trend"] += 1
                reasons.append("Operating margin improving")

        if metrics.get("fcf_yield"):
            max_bounds["trend"] += 1  
            if improving(d.get("fcf_yields_fy_h", []), threshold=0.5):
                scores["trend"] += 1
                reasons.append("FCF Yield rising")
            
        if metrics.get("nd_ebit"):
            max_bounds["trend"] += 1
            if deteriorating(d.get("net_debt_to_ebitda_hs", []), threshold=-0.2):            
                scores["trend"] += 1
                reasons.append("Net Debt to EBITDA decreasing")

        if metrics.get("div_payout"):
            max_bounds["trend"] += 1            
            if deteriorating(d.get("dividend_payout_ratio_fy_h", []), threshold=-0.2):    
                scores["trend"] += 1
                reasons.append("Div. Payout decreasing")
        
        if metrics.get("ev_to_sales"):
            max_bounds["trend"] += 1
            ev_to_sales_h = d.get("ev_to_sales_hs", [])[-3:]
            if ticker == 'CVX':
                print ('ev_to_sales_h', ev_to_sales_h)
            if deteriorating(ev_to_sales_h):
                scores["trend"] += 1
                reasons.append("EV/Sales decreasing")

        if metrics.get("pe"):
            max_bounds["trend"] += 1           
            if deteriorating(d.get("pe_fy_h", []), threshold=-0.25):
                scores["trend"] += 1
                reasons.append("P/E decreasing")
            
        if metrics.get("ev_to_ebitda"):
            max_bounds["trend"] += 1
            if deteriorating(d.get("ev_ebitda", []), threshold=0.25):
                scores["trend"] += 1
                reasons.append("EV/EBITDA decreasing")

        if metrics.get("eps"):
            max_bounds["trend"] += 2
            eps_ttm = d.get("eps_dilu_ttms")
            eps_forecast = d.get("eps_frcst_next_fy")
            eps_series = d.get("eps_dil_fy_hs", [])
            eps_latest = eps_series[-1] if eps_series else None
            
            if eps_ttm is not None and eps_ttm > 0:
                if trend_improving(ticker, eps_series, True):
                    scores["trend"] += 1
                    reasons.append("EPS improving")
                elif eps_ttm > 1.00:
                    scores["trend"] += 0.5
                    reasons.append("EPS dipping but remains robust per share")
                    
                if eps_latest is not None and eps_forecast is not None:
                    if eps_forecast > eps_latest * 1.15:
                        scores["trend"] += 1
                        reasons.append("Strong forecasted EPS growth")
                    elif eps_forecast < eps_latest * 0.85:
                        scores["trend"] -= 1
                        reasons.append("Forecasted EPS decline")

        # --- NORMALIZATION & SECTOR WEIGHTING ---
        norm_metrics = {}
        for key in weights.keys():
            norm_metrics[key] = safe_normalize(scores[key], max_bounds[key])
 
        #     if ticker == 'CVX' and key == 'valuation':
        #         print ('norm_metrics[key]',norm_metrics[key])
                

        if ticker == 'CVX':
            m2 = 'valuation'
            print (ticker, '---------')
            print ('scores[m2]', scores[m2])
            print ('safe_normalize(scores[key], max_bounds[key])', safe_normalize(scores[m2], max_bounds[m2]))
            print ('norm_metrics[m2]',norm_metrics[m2])
            print ('weights[m2]', weights[m2])
            print ('trend score', round(norm_metrics['trend'] * weights['trend'], 2))
            print ('quality score', round(norm_metrics[m2] * weights[m2], 2))
                   
        
        final_score = sum(norm_metrics[m] * weights[m] for m in weights.keys())
        final_score = round(final_score, 2)

        # Decision Engine
        if final_score >= 0.40: rating = "SB"
        elif final_score >= 0.30: rating = "BUY"
        elif final_score >= 0.20: rating = "HOLD"
        elif final_score >= 0.10: rating = "AVOID"
        else: rating = "SELL"

        if ticker == 'CVX':
        
            print ('final_score2', final_score)

        
        results[ticker] = {
            "score": final_score,
            "rating": rating,
            "reasons": reasons,
            "classification": cls,
            "component_scores": {
                f"normalized_{k}": v for k, v in norm_metrics.items()
            }
        }
        # Inject standard component scores as well
        for k, v in scores.items():
            results[ticker]["component_scores"][f"{k}_score"] = v
        for k in weights.keys():
            results[ticker]["component_scores"][f"weighted_{k}"] = norm_metrics[k] * weights[k]

    return results

In [33]:
df_3, dict_3 = get_formatted_data(energy, False)
metrics = { "roic": True, "interest_coverage": True,  "op_margin": True, "fcf_yield": True, "nd_ebit": True, "ev_to_ebitda": True, "rev_growth": True,
           "current_ratio": True, "fcf_p_share": True, "buyback_ratio": True, 
           "fcf_h": True,  "ev_to_sales": True, "pe": True, "pr1yr": True, "dy": True, "div_payout": True, "eps": True, "bc": True }
results = evaluate_energy_stocks2(df_3.index.tolist(), dict_3, metrics)
df_6 = get_results_report(results)
mask = (df_6['class.'] == 'integrated')
df_6[mask].sort_values(by=['class.','score'], ascending=[True,False])

Error in get_jsondata_from_file opening file for BP [Errno 2] No such file or directory: 'D:/Udemy/2026-Python3-ErikBanas/Section53_PythonForFinance/redo/dividends/BP.json'
[4.1, 2.82, 1.82, 2.28, 1.21, 3.71, 1.12, 1.29, 2.11]
percentile 0.6666666666666666
adjusted percentile 0.33333333333333337
score 1
ev_to_sales_h [1.52, 1.48, 1.78]
CVX ---------
scores[m2] 0.0
safe_normalize(scores[key], max_bounds[key]) 0.0
norm_metrics[m2] 0.0
weights[m2] 0.14
trend score 0.0
quality score 0.0
final_score2 -0.1

,rating,score,class.,reason
ticker,,,,
CNQ,SB,0.41,integrated,"[Poor (0.0) EV/Sales, Attractive (0.889) P/E, ..."
TTE,SB,0.40,integrated,"[Good (0.667) EV/Sales, Attractive (0.778) P/E..."
SHEL,BUY,0.38,integrated,"[Attractive (0.889) EV/Sales, Good (0.667) P/E..."
COP,BUY,0.32,integrated,"[Neutral (0.222) EV/Sales, Fair (0.444) P/E, A..."
XOM,HOLD,0.22,integrated,"[Fair (0.444) EV/Sales, Fair (0.333) P/E, Fair..."
CVE,AVOID,0.13,integrated,"[Good (0.556) EV/Sales, Good (0.556) P/E, Fair..."
OXY,SELL,0.08,integrated,"[Neutral (0.111) EV/Sales, Poor (0.0) P/E, Att..."
CVX,SELL,-0.10,integrated,"[Fair (0.333) EV/Sales, Neutral (0.111) P/E, N..."
E,SELL,-0.11,integrated,"[Attractive (0.778) EV/Sales, Neutral (0.222) ..."

In [9]:

def get_results_report(result):
    
    values = [v for k, v in results.items()]
    keys = [k for k, v in results.items()]
    df_5 = pd.DataFrame({'key': keys, 'value': values})
    
    buys, ratings, rois, scores, reasons, classifications = [], [], [], [], [], []
    
    for index, row in df_5.iterrows():
        buys.append(row['key'])        
        ratings.append(row['value']['rating'])
        scores.append(row['value']['score'])
        reasons.append(row['value']['reasons'])
        classifications.append(row['value']['classification'])
    
    df_6 = pd.DataFrame({'ticker': buys, 'rating': ratings, 'score': scores, 'class.': classifications})
    df_6 = pd.DataFrame({'ticker': buys, 'rating': ratings, 'score': scores, 'class.': classifications, 'reason': reasons})
    
    # , 
    df_6.reset_index(inplace=True)
    df_6.set_index(['ticker'], inplace=True)
    df_6.drop(columns=['index'], inplace=True)
    
    betas = pd.DataFrame(get_beta_5_year_for_df(df_6))
    betas.set_index(['ticker'], inplace=True)
    
    for x in df_3.columns:
        
        if x == 'sector' or x == 'country' or x == 'revenue_growth' or x == "classification" or x == "pe_fy_h": 
            continue

        # if x == "roic":
        #     df_6['roic'] = df_3[x]
        # elif x == "current_ratio":
        #     df_6['current_ratio'] = df_3[x]
        # elif x == "fcf_p_share_ttm":
        #     df_6['fcf_p_share_ttm'] = df_3[x]
        # elif x == "interest_coverage":
        #     df_6['interest_coverage'] = df_3[x]
        # elif x == 'net_debt_to_ebitda':
        #     df_6['net_d_to_ebit'] = df_3[x]
        # elif x == 'fcf_pos_years_5y':
        #     df_6['fcf_pos_5y'] = df_3[x]
        # elif x == "operating_margin_ttms":
        #     df_6['om_ttms'] = df_3[x]
        # elif x == "operating_margin_ttm":
        #     df_6['om_fq_h'] = df_3[x]
        # elif x == "om_ttm":
        #     df_6['om_fq_h'] = df_3[x]
        # elif x == "ev_to_sales_current":
        #     df_6['ev_sales_cur'] = df_3[x]
        # elif x == "price_return_1y":
        #     df_6['ret_1yr'] = df_3[x]
        # elif x == "eps_frcst_next_fy":
        #     df_6['eps_frcst_nxt_fy'] = df_3[x]
        # elif x == "net_debt_to_ebitda_hs":
        #     df_6['net_dbt'] = df_3[x]
        # el
        # elif x == "roic":
        #     pass
        # else:
        #     df_6[x] = df_3[x]
            
    # df_6['beta'] = betas['beta']
    
    return df_6

df_6 = get_results_report(results)

NameError: name 'results' is not defined

In [8]:
def dividend_cagr(dividend_history):

    """
    Example input:
     [ 
        { "date": "2026-01-01", "amount": 1.34 },
        { "date": "2026-04-01", "amount": 1.40 },
     }
    oldest -> newest
    """
        
    yearly_dividends = defaultdict(float)
    
    for payment in dividend_history:
        year = int(payment["date"][:4])
        yearly_dividends[year] += payment["amount"]


    if not yearly_dividends or len(yearly_dividends) < 2:
        return None
    
    dividend_history = list(yearly_dividends.values())
    
    start = dividend_history[0]
    end = dividend_history[-1]

    if start <= 0:
        return None

    years = len(dividend_history) - 1

    cagr = ((end / start) ** (1 / years)) - 1

    return cagr * 100

In [378]:
g = [{'date': '2019-06-03', 'amount': 0.305}, {'date': '2019-09-03', 'amount': 0.305}, {'date': '2019-12-02', 'amount': 0.42}, 
     {'date': '2020-03-02', 'amount': 0.42}, {'date': '2020-06-01', 'amount': 0.42},
     {'date': '2020-09-01', 'amount': 0.42}, {'date': '2020-12-01', 'amount': 0.43}, {'date': '2021-03-01', 'amount': 0.43}, {'date': '2021-06-01', 'amount': 0.43}, {'date': '2021-09-01', 'amount': 0.43}, 
     {'date': '2021-12-01', 'amount': 0.46}, {'date': '2022-01-14', 'amount': 0.2}, {'date': '2022-03-01', 'amount': 0.46}, {'date': '2022-04-14', 'amount': 0.3}, {'date': '2022-06-01', 'amount': 0.46},
     {'date': '2022-07-15', 'amount': 0.7}, {'date': '2022-09-01', 'amount': 0.46}, {'date': '2022-10-14', 'amount': 1.4}, {'date': '2022-12-01', 'amount': 0.51}, {'date': '2023-01-13', 'amount': 0.7}, 
     {'date': '2023-03-01', 'amount': 0.51}, {'date': '2023-04-14', 'amount': 0.6}, {'date': '2023-06-01', 'amount': 0.51}, {'date': '2023-07-14', 'amount': 0.6}, {'date': '2023-09-01', 'amount': 0.51}, 
     {'date': '2023-10-16', 'amount': 0.6}, {'date': '2023-12-01', 'amount': 0.58}, {'date': '2024-03-01', 'amount': 0.58}, {'date': '2024-03-01', 'amount': 0.2}, {'date': '2024-06-03', 'amount': 0.58}, 
     {'date': '2024-06-03', 'amount': 0.2}, {'date': '2024-09-03', 'amount': 0.58}, {'date': '2024-09-03', 'amount': 0.2}, {'date': '2024-12-02', 'amount': 0.78}, {'date': '2025-03-03', 'amount': 0.78},
     {'date': '2025-06-02', 'amount': 0.78}, {'date': '2025-09-02', 'amount': 0.78}, 
     {'date': '2025-12-01', 'amount': 0.84}, {'date': '2026-03-02', 'amount': 0.84}, {'date': '2026-06-01', 'amount': 0.84}]
dividend_cagr(g)

7.2390976483807545

In [7]:
def sequence_has_zeros_or_none(items):
    items = [0 if x is None else x for x in items]
    return len([x for x in items if x == 0]) > 0 


def get_jsondata_from_file(folder, ticker):
    try:        
        with open(f"{PATH}{folder}/{ticker}.json", 'r') as file:
            data = json.load(file)
            if len(data) == 0:
                return None
    except Exception as e:
        print (f'Error in get_jsondata_from_file opening file for {ticker} {e}')
        return None
    else:
        return data


def has_acceptable_beta(min, max, beta):
    try:
        if beta is None:
            return False
            
        beta = beta['value']
        
        if beta is None:
            return False
    except Exception as e:
        print (f'Error in get_jsondata_from_file opening file for {ticker} {e}')
        return False
    else:
        return beta > 0 or beta < 10
                    
def convert_none_to_zero_in_list(items):
    return [0 if x is None else x for x in items]



def list_has_at_least_one_value(items):    
    x2 = convert_none_to_zero_in_list(items)
    x2 = [x for x in x2 if x != 0]
    return len(x2) >= 1


def remove_nones_from_list(items):
    return [x for x in items if x != 0 and x is not None]
    

def get_history_indicator_values(ticker, data, indicator_id, num_items):
    roic = []
    try:
        roic = next((item for item in data if item["id"] == indicator_id), None) 
        if roic is None:
            return None
        roic = roic['value']
        roic = roic[:num_items]
        roic = roic[::-1]
    except Exception as e:
        print (f'Error in get_history_indicator_values.{ticker} {e}. Indicator: {indicator_id}')
    else:
        return roic
        
    return None

def get_single_value(ticker, data, indicator_id):
    try:
        value = next((item for item in data if item["id"] == indicator_id), None)
    except Exception as e:
        print (f'Error in get_single_value.{ticker} {e}. Indicator: {indicator_id}')
    else:
        return value.get('value') if value is not None else None

In [6]:
def get_stock_info_from_api(ticker):
    url = f'https://api.insightsentry.com/v3/symbols/NYSE%3A{ticker}/info'
    json_data = None
    response = requests.get(url, headers=HEADERS) 
    try:
        if response.status_code == 200:
            json_data = response.json()
        else:
            url = f'https://api.insightsentry.com/v3/symbols/NASDAQ%3A{ticker}/info'
            response = requests.get(url, headers=HEADERS)          
            if response.status_code == 200:
                json_data = response.json()
    except Exception as e:
        print (f'Error in get_stock_info_from_api {ticker}: {e}')        
    else:
        return json_data

def get_stock_info(ticker, key, overwrite = False):
    json_data = None
    result = None
    try:
        if overwrite == True:
            os.remove(f"{PATH}info/{ticker}.json")
            
        if os.path.exists(f"{PATH}info/{ticker}.json"):
            file_path = f'{PATH}info/{ticker}.json'
            with open(f"{PATH}info/{ticker}.json", 'r') as file:
                data = json.load(file)
                result = data.get(key)
        else:
            json_data = get_stock_info_from_api(ticker)
            if json_data is not None:
                with open(f"{PATH}info/{ticker}.json", "w") as f:
                    json.dump(json_data, f, indent=4)
                result = json_data.get(key)
            else:
                print (f'No info returned for {ticker}')
    except Exception as e:
        print (f'Error in get_stock_total_shares_outstanding {ticker}: {e}')
        return None
    else:
        return result

In [4]:
def count_positive_values_from_list(items):
    items = convert_none_to_zero_in_list (items)
    return len([x for x in items if x > 0])
    
def get_country_from_website_url(url):
    www_index = url.find('www')
   
    if www_index != -1:
        return "US"
    else:
        last_index_l = url.rfind('.')
        end = url[last_index_l + 1:].upper()
        if end == 'COM':
            return 'US'
        else:
            return url[last_index_l + 1:].upper()


def repair_sequence(items):

    if items[-1] is None:
        return None
        
    try:
            
        eps_fy_h_2 = []
        
        num_added = False
        
        for i in range(len(items)):
            if items[i] is not None:
                items.append(items[i])
                num_added = True
            else:
                if i != 0:
                    if num_added == True:
                        return None
    
    except Exception as ex:
        print (f'Error repair_sequance {e}')
        return None
        
    return items

    

    
def get_stock_eps(ticker):

    url = f'https://api.insightsentry.com/v3/symbols/NYSE%3A{ticker}/info'
    json_data = None
    response = requests.get(url, headers=HEADERS)
    if response.status_code == 200:
        json_data = response.json()
        if json_data is None:
            return json_data.get("earnings_per_share_basic_ttm")
    else:
        url = f'https://api.insightsentry.com/v3/symbols/NASDAQ%3A{ticker}/info'
        response = requests.get(url, headers=HEADERS)
        if response.status_code == 200:
            json_data = response.json()
            if json_data is not None:
                return json_data.get("earnings_per_share_basic_ttm")

    return None


def get_one_year_ago_price(ticker):
    try:
        
        df = get_df_from_csv(ticker)
        sdate = datetime.now() - relativedelta(years=1)
        
        edate = sdate + relativedelta(days=4)
        
        sdate = str(datetime.strptime(f"{sdate.year}-{sdate.month}-{sdate.day-1}",'%Y-%m-%d').date())
        # print ('get_one_year_ago_price 4')
        
        edate = str(datetime.strptime(f"{edate.year}-{edate.month}-{edate.day-1}",'%Y-%m-%d').date())
        # print ('get_one_year_ago_price 5')
        
        # print (1, sdate, edate)
    
        sdate, edate = get_valid_dates(df, sdate, edate)
        
        # print (2, sdate, edate)
        
        d = float(df.loc[sdate:sdate]['close'].item())
        # print ('get_one_year_ago_price 6')
        
    except Exception as e:
        print(f'Exception in get_one_year_ago_price ticker {ticker}. {e}')
    else:
        return d


def get_valid_dates(df, sdate, edate):
    
    try:
        # mask = (df['date'] > sdate) & (df['date'] <= edate) 
        sm_df = df.loc[sdate:edate]
        if not sm_df.empty:
            sm_date = str(sm_df.index.min()).split(' ')[0]
            last_date = str(sm_df.index.max()).split(' ')[0]
            
            date_leading = str(sm_df.index.min()).split(' ')[0] #'-'.join(('0' if len(x) < 2 else '')+x for x in sm_date.split('-'))
            date_ending = str(sm_df.index.max()).split(' ')[0]  #'-'.join(('0' if len(x) < 2 else '')+x for x in last_date.split('-'))
            # print(date_leading, " ", date_ending)
        else:
            
            return None, None
    except Exception:
        print("Errro in get_valid_dates Date Corrupted")
    else:
        return date_leading, date_ending


def get_expected_growth_cagr (ticker, revenues):

    try:
        start_idx = next((i for i, val in enumerate(revenues) if val > 0), None)

        if start_idx is None or start_idx == len(revenues) - 1:
            return 0.0
        
        # CAGR
        years = len(revenues) - 1
        
        cagr = (revenues[-1] / revenues[start_idx]) ** (1 / years) - 1
    except Exception as e:
        print (f'Error in get_expected_growth_cagr {ticker} {revenues}. {e}')
    else:
        return cagr


def get_close_from_api(ticker):
  
    url = f'https://api.insightsentry.com/v3/symbols/quotes?codes=NYSE%3A{ticker}&extended=false&dadj=false'
    json_data = None
    close = -1
    response = requests.get(url, headers=HEADERS)
    if response.status_code == 200:
        json_data = response.json()
        
        if json_data['data'][0].get('message') == None:
            close = json_data['data'][0].get('prev_close_price')
        else:
            url = f'https://api.insightsentry.com/v3/symbols/quotes?codes=NASDAQ%3A{ticker}&extended=false&dadj=false'
            response = requests.get(url, headers=HEADERS)
            if response.status_code == 200:
                json_data = response.json()
                if json_data['data'][0].get('message') == None:
                    close = json_data['data'][0].get('prev_close_price')
                    
    return close, json_data
        

def get_close(ticker, overwrite=False):
    close = -1
    try:

        if overwrite == True:
            os.remove(f"{PATH}quotes/{ticker}.json")
            
        if os.path.exists(f"{PATH}quotes/{ticker}.json"):
            
            file_path = f'{PATH}quotes/{ticker}.json'
            file_time = os.path.getmtime(file_path)
            if (time.time() - file_time) > (5 * 86400):
                
                close, json_data = get_close_from_api(ticker)
                
                if close > -1:
                    with open(f"{PATH}quotes/{ticker}.json", "w") as f:
                        json.dump(json_data, f, indent=4)
            else:
                with open(f"{PATH}quotes/{ticker}.json", 'r') as file:
                    data = json.load(file)
                    close = data['data'][0].get('prev_close_price')
                
        else:
            close, json_data = get_close_from_api(ticker)
            if close > -1:
                with open(f"{PATH}quotes/{ticker}.json", "w") as f:
                    json.dump(json_data, f, indent=4)
                    
    except Exception as e:
        print (f'Error in get_close: {e}')

    return close
    

def get_market_cap_from_api(ticker):
    
    url = f'https://api.insightsentry.com/v3/symbols/quotes?codes=NYSE%3A{ticker}&extended=false&dadj=false'
    json_data = None
    market_cap = -1
    response = requests.get(url, headers=HEADERS)
    if response.status_code == 200:
        json_data = response.json()
        if json_data['data'][0].get('message') == None:
            market_cap = json_data['data'][0].get('market_cap')
        else:
            url = f'https://api.insightsentry.com/v3/symbols/quotes?codes=NASDAQ%3A{ticker}&extended=false&dadj=false'
            response = requests.get(url, headers=HEADERS)
            if response.status_code == 200:
                json_data = response.json()
                if json_data['data'][0].get('message') == None:
                    market_cap = json_data['data'][0].get('market_cap')
        return market_cap, json_data

    
def get_market_cap(ticker):
    json_data = None
    market_cap = -1
    try:
        if os.path.exists(f"{PATH}quotes/{ticker}.json"):
            
            file_path = f'{PATH}quotes/{ticker}.json'
            file_time = os.path.getmtime(file_path)
            if (time.time() - file_time) > (5 * 86400):
                
                market_cap, json_data = get_market_cap_from_api(ticker)
                
                if market_cap > -1:
                    with open(f"{PATH}quotes/{ticker}.json", "w") as f:
                        json.dump(json_data, f, indent=4)
            else:
                with open(f"{PATH}quotes/{ticker}.json", 'r') as file:
                    data = json.load(file)
                    market_cap = data['data'][0].get('market_cap')
                
        else:
            market_cap, json_data = get_market_cap_from_api(ticker)
            if market_cap > -1:
                with open(f"{PATH}quotes/{ticker}.json", "w") as f:
                    json.dump(json_data, f, indent=4)
                    
    except Exception as e:
        print (f'Error: {e}')

    return market_cap



    
def get_df_from_csv(ticker):
    
    # Try to get the file and if it doesn't exist issue a warning
    try:

        if ticker not in tickers_to_skip:
            df = pd.read_csv(PATH + 'converted/' + ticker + '.csv')
            # df['date2'] = pd.DatetimeIndex(['date'])
            df = df.set_index(pd.to_datetime(df['date']))
            df.drop(columns=['date'], inplace=True)
            # df = df.loc[S_DATE_STR:E_DATE_STR]
            return df
        else:
            return None
        # df = delete_unnamed_cols(df)
        
    except FileNotFoundError:
        missing_tickers.append(ticker)
        print(f"File for ticker {ticker} doesn't exist")
        return None
        
def get_rois_for_stocks(stock_df, sdate, edate):

    tickers = []
    classifications = []
    rois = []
    company_names = []
    for index, row in stock_df.iterrows():
        df = get_df_from_csv(row['ticker'])
        if df is None:
            pass
        else:
            mask = (df.index > sdate) & (df.index <= edate)
            
            if len(df.loc[mask]) > 0:
                
                sdate2, edate2 = get_valid_dates(df, sdate, edate)
                roi = roi_between_dates(df, sdate2, edate2)
                # if roi > 0:
                rois.append(roi)
                tickers.append(row['ticker'])
                company_names.append(row['company_name'])
                classifications.append(row['classification'])

    return pd.DataFrame({'Ticker' : tickers,  'Company': company_names , 'classification': classifications, 'ROI' : rois})

def roi_between_dates(df, sdate, edate):
    try: 
        start_val = df.loc[sdate,'close'] 
        end_val = df.loc[edate,'close']
        # print(f"start_val: {start_val}")
        # print(f"end_val: {end_val}")
        
        roi = ((end_val - start_val) / start_val)
    except Exception:
        print("Data Corrupted")
    else:
        return roi



def classify_beta(beta):
    if beta is None:
        return "Unknown"
    elif beta < 0.8:
        return "Low Risk"
    elif beta <= 1.2:
        return "Market-like"
    else:
        return "High Risk"

def get_beta(ticker):
    try:
            
        with open(f'{PATH}dividends/{ticker}.json', 'r') as file:
            data = json.load(file)['data']        
            beta = next((item for item in data if item["id"] == 'beta_5_year'), None)['value']        
            return beta
    except Exception as e:
        print (f"Error in get_beta {ticker}")
    return None
    
def get_beta_5_year_for_df(df):
    betas = []
    for index, row in df.iterrows():
        beta = get_beta(index)
        if beta is not None:
            betas.append({'ticker': index, 'beta': round(beta, 2)})
        else:
            print (f'get_beta_5_year_for_df says: No beta for {index}')
    return betas
    
def get_growth_rates(revenues):
    growth_rates = []
    
    for i in range(1, len(revenues)):
        previous = revenues[i - 1]
        current = revenues[i]
        growth = (current - previous) / previous
        growth *= 100
        growth_rates.append( np.around(growth, decimals=3).item())
    
    return growth_rates

In [6]:
# x2 = [None, 10, 10, -10]


# count_positive_values_from_list(x2)

# # x = [None, None, 379.013898292971]
# # if list_has_at_least_one_value(x) == True:
# #     remove_nones_from_list(enterprise_value_ebitda_fq_h)
# # else:
# #     print ('invalid')

# [8.57, 9.26, null]
# [78962000000, 83362000000, 80039000000, 83161000000]


# def tech_valuation_screen(ticker, financials):
#     """
#     financials: {
#         'rev_growth': 0.15,      # 15% YoY Revenue Growth
#         'fcf_margin': 22,        # 22% FCF Margin
#         'fcf_yield': 6.5,        # 6.5% FCF Yield
#         'peg_ratio': 1.2,        # Price/Earnings to Growth
#         'is_profitable': True
#     }
#     """
#     # 1. THE QUALITY CHECK (Must be a real business)
#     # Tech leaders usually have 20%+ margins. 15% is our 'value' floor.
#     is_high_quality = financials['fcf_margin'] > 15 and financials['is_profitable']
    
#     # 2. THE GROWTH CHECK (No Value Traps)
#     # Undervalued tech is only a buy if it's still growing.
#     has_momentum = financials['rev_growth'] > 0.08  # 8% minimum growth
    
#     # 3. THE VALUATION CHECK (Is it actually cheap?)
#     # PEG < 1.0 is the gold standard for 'Undervalued'
#     # FCF Yield > 5% is very high for Tech
#     is_undervalued = financials['peg_ratio'] < 1.5 and financials['fcf_yield'] > 5.0

#     # --- DECISION ENGINE ---
#     if is_high_quality and has_momentum and is_undervalued:
#         return f"{ticker}: RARE TECH VALUE (Growth at a Discount)"
    
#     elif is_high_quality and is_undervalued:
#         return f"{ticker}: MATURE CASH COW (Stable, but slow growth)"
    
#     elif is_undervalued:
#         return f"{ticker}: SPECULATIVE VALUE (Cheap for a reason?)"
        
#     else:
#         return f"{ticker}: PASS (Overvalued or Low Quality)"

# # Example Usage:
# # stock_data = {'rev_growth': 0.12, 'fcf_margin': 25, 'fcf_yield': 5.5, 'peg_ratio': 0.9, 'is_profitable': True}
# # print(tech_valuation_screen("TICKER", stock_data))